= Mise en place d'un reverse proxy

L'objectif de ce proxy est d'intercepter le trafic entrant des ports 80/443, puis de les rediriger vers un des conteneurs (docker) proposant le bon service concernée. j'utiliserai pour cela nginx qui analysera la reqête HTTP en fonction du FQDN proposé

== Gestion Docker

Le proxy sera cloisonné dans un container, tous comme les services web qui sont chacun isolés dans leu conteneur respectif.

== Procédure

La configuration du proxy ce trouve dans '*/srv/web/reverse_proxy*'

* Clonage du proxy depuis github
* Création d'un fichier 'docker-compose.yml'
* Configuration du fichier 'Dockerfile'
* Création d'un fichier 'backend-not-found.html'
* Configuration du fichier 'default.conf'
* 

Fait partie du projet github : https://github.com/docker-jb35/reverse_proxy

=== Procédure de clonage :

[source,shell]
----
#pensez à ajouter le clef ssh
mkdir /srv/web && cd /srv/web
git clone git@github.com:docker-jb35/reverse_proxy.git
----


=== Configuration de la partie Docker

==== Configuration du fichier 'docker-compose.yml'

Ce fichier va permettre d'automatiser docker et de lancer le proxy grâce à ses 3 commandes.

[source,shell]
----
#Construction de l'image
docker composer build
#Génération du container (-d) permet de lancer en arrière-plan.
docker compose up (-d)
#Arrête du service et destruction du container
docker compose down
# Affiche les logs du services.
docker compose logs

#Lance un nouveau conteneur et execute la commande en passant par le scripte spécifié avec le mot clef : ENTRYPOINT
docker compose run 

#Executer une commande dans le même contexte du container lancé avec la commande 'docker compose up (-d)'
docker compose exec
----

.fichier docker-compose.yml
[source,yaml]
----
version: '2'
services:
  proxy:
    build: ./
    networks:
     - wiki
     - glpi
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./var/ssl:/etc/ssl/certs/nginx/
     - ./var/le:/etc/letsencrypt/
networks:
  wiki:
    external: true
    name: wiki-antora_service_web
  glpi:
    external: true
    name: glpi_glpi
----

==== Configuration du fichier 'Dockerfile'

L'image par défaut de nginx ne contient qu'un site par défaut, et il faut modifier son comportement, d'où l'intérêt du fichier de configuration 'Dockerfile' celui-ci va lancer différentes instructions pendant l'appel 'docker compose build' qui généra une image.


.fichier "DockerFile"
[source,yaml]
----
# Récupère l'image nginx sur https://hub.docker.com/_/nginx
FROM nginx

# Copies le différents fichier de configuration nécessaire au bon fonctionnement de nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./backend-not-found.html /var/www/html/backend-not-found.html
COPY ./includes/ /etc/nginx/includes/
COPY ./scriptes/entrypoint.sh /entrypoint.sh
COPY ./scriptes/let-encrypt.sh /let-encrypt.sh

# Création d'une variable d'environnement pour signaler à dpkg qu'il n'y a pas d’interaction
ENV DEBIAN_FRONTEND=noninteractive
RUN \
    chmod +x /entrypoint.sh && \
    chmod +x /let-encrypt.sh && \
    apt update -y && apt-get install certbot python3-certbot-nginx -y 

# Point d'accès des commande lancée avec (run et exec)
ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "nginx", "-g", "daemon off;"  ]
----


=== Création du fichier 'backend-not-found.html'

Création d'un fichier html renvoyant une erreur si aucun service web n'a été trouvé.

[source,html]
----
<html>
    <head>
        <title>Reverse Proxy: Not Found!</title>
    </head>
    <body>
        <h2>Reverse Proxy: Not Found!</h2>
    </body>
</html>
----

=== Création du fichier de configuration ngxinx "default.conf"

Créer le fichier *default.conf* dans le dossier *reverse_proxy*

[source,conf]
----
# Service Web Wiki.
 log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

server {
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name wiki.jlab.ovh;

    # Path for SSL config/key/certificate

    ssl_certificate         SSL_CERT_1;
    ssl_certificate_key     SSL_KEY_1;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://wiki.jlab.ovh;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}

# Service Web GLPI
server {
    listen 80;
    listen 443 ssl;
    http2 on;

    server_name glpi.jlab.ovh;

    # Path for SSL config/key/certificate
    ssl_certificate         SSL_CERT_2;
    ssl_certificate_key     SSL_KEY_2;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://glpi.jlab.ovh;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}

# Default
server {
    listen 80 default_server;

    server_name _;
    root /var/www/html;

    charset UTF-8;

    error_page 404 /backend-not-found.html;
    location = /backend-not-found.html {
        allow all;
    }
    location / {
        return 404;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}
----

=== Mise en place du fichier 'docker-compose.yml'

Créer le fichier *docker-compose.yml* dans le dossier *reverse_proxy*



=== Configuration de nginx

[NOTE]
====
Suivi tuto:
https://phoenixnap.com/kb/docker-nginx-reverse-proxy[Nginx reverse proxy sur docker]
====