= Mise en place d'un reverse proxy

L'objectif de ce proxy est d'intercepter le trafic entrant des ports 80/443, puis de les rediriger vers un des conteneurs (docker) proposant le bon service concernée. j'utiliserai pour cela nginx qui analysera la reqête HTTP en fonction du FQDN proposé

== Gestion Docker

Le proxy sera cloisonné dans un container, tous comme les services web qui sont chacun isolés dans leu conteneur respectif.

== Procédure

La configuration du proxy ce trouve dans '*/srv/web/reverse_proxy*'

* *Clonage du projet depuis Github*
* *Configuration de la partie Docker*
** Configuration du fichier '*docker-compose.yml*'
*** fichier *docker-compose.yml*
** Configuration du fichier '*Dockerfile*'
** Scriptes *scriptes/entrypoint.sh* et *scriptes/letsencrypt.sh*
* *Configuration de nginx*
** Création d'un fichier '*backend-not-found.html*'
** Configuration du fichier '*default.conf*'




** Configuration des fichiers *includes/ssl.conf* et *includes/proxy.conf*



Fait partie du projet github : https://github.com/docker-jb35/reverse_proxy

=== Clonage du projet depuis Github :

[source,shell]
----
#pensez à ajouter le clef ssh
mkdir /srv/web && cd /srv/web
git clone git@github.com:docker-jb35/reverse_proxy.git
----


=== Configuration de la partie Docker

==== Configuration du fichier 'docker-compose.yml'

Ce fichier va permettre d'automatiser docker et de lancer le proxy grâce à ses 3 commandes :

[source,shell]
----
# Construction de l'image
docker composer build
# Génération du container (-d) permet de lancer en arrière-plan.
docker compose up (-d)
# Arrête du service et destruction du container
docker compose down
# Affiche les logs du services.
docker compose logs

# Lance un nouveau conteneur et execute la commande en passant par le scripte spécifié avec le mot clef : ENTRYPOINT
docker compose run 

# Executer une commande dans le même contexte du container lancé avec la commande 'docker compose up (-d)'
docker compose exec
----

.fichier docker-compose.yml
[source,yaml]
----
version: '2'
services:
  proxy:
    build: ./
    networks:
     - wiki
     - glpi
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./etc/ssl:/etc/ssl/certs/nginx/
     - ./etc/le:/etc/letsencrypt/
networks:
  wiki:
    external: true
    name: wiki-antora_service_web
  glpi:
    external: true
    name: glpi_glpi
----

==== Configuration du fichier 'Dockerfile'

L'image par défaut de nginx ne contient qu'un site par défaut, et il faut modifier son comportement, d'où l'intérêt du fichier de configuration 'Dockerfile' celui-ci va lancer différentes instructions pendant l'appel '*docker compose build*' qui généra une image.


.fichier "DockerFile"
[source,yaml]
----
# Récupère l'image nginx sur https://hub.docker.com/_/nginx
FROM nginx

# Copies le différents fichier de configuration nécessaire au bon fonctionnement de nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./backend-not-found.html /var/www/html/backend-not-found.html
COPY ./includes/ /etc/nginx/includes/
COPY ./scriptes/entrypoint.sh /entrypoint.sh
COPY ./scriptes/let-encrypt.sh /let-encrypt.sh

# Création d'une variable d'environnement pour signaler à dpkg 
# qu'il n'y a pas d’interaction
ENV DEBIAN_FRONTEND=noninteractive

# Modifie les autorisation d’exécution des 2 scriptes ci-dessous,
# mais à jour "l'image"
RUN \
    chmod +x /entrypoint.sh && \
    chmod +x /let-encrypt.sh && \
    apt update -y && apt-get install certbot python3-certbot-nginx -y 

# Point d'accès des commande lancée avec (run et exec)
ENTRYPOINT [ "/entrypoint.sh" ]

# Argument par défaut lancée au scripte plus haut
CMD [ "nginx", "-g", "daemon off;"  ]
----

==== Scriptes *scriptes/entrypoint.sh* et *scriptes/letsencrypt.sh*

Mise en place dde 2 scripte en test afin de mettre en place lestsencrypt.

Le fichier *scriptes/entrypoint.sh* est appelée depuis les commandes '*docker compose up*', '*docker compose run*' et '*docker compose exec*'

.fichier 'scriptes/entrypoint.sh'
[,shell]
----
#!/bin/sh

#setup ssl keys, export to pass them to le.sh
echo "ssl_key_wiki=${SSL_KEY_1:=wiki.key}, ssl_cert=${SSL_CERT_1:=wiki.crt}, ssl_chain_cert=${SSL_CHAIN_CERT_1:=wiki.chain}"
echo "ssl_key_glpi=${SSL_KEY_2:=glpi.key}, ssl_cert=${SSL_CERT_2:=glpi.crt}, ssl_chain_cert=${SSL_CHAIN_CERT_2:=glpi.chain}"
export LE_SSL_KEY_1=/etc/ssl/certs/nginx/${SSL_KEY_1}
export LE_SSL_KEY_2=/etc/ssl/certs/nginx/${SSL_KEY_2}
export LE_SSL_CERT_1=/etc/ssl/certs/nginx/${SSL_CERT_1}
export LE_SSL_CERT_2=/etc/ssl/certs/nginx/${SSL_CERT_2}
export LE_SSL_CHAIN_CERT_1=/etc/ssl/certs/nginx/${SSL_CHAIN_CERT_1}
export LE_SSL_CHAIN_CERT_2=/etc/ssl/certs/nginx/${SSL_CHAIN_CERT_2}

sed -i "s|SSL_KEY_1|${LE_SSL_KEY_1}|g"  /etc/nginx/conf.d/default.conf 2>/dev/null
sed -i "s|SSL_CERT_1|${LE_SSL_CERT_1}|g"  /etc/nginx/conf.d/default.conf 2>/dev/null
sed -i "s|SSL_CHAIN_CERT_1|${LE_SSL_CHAIN_CERT_1}|g"  /etc/nginx/conf.d/default.conf 2>/dev/null

sed -i "s|SSL_KEY_2|${LE_SSL_KEY_2}|g"  /etc/nginx/conf.d/default.conf 2>/dev/null
sed -i "s|SSL_CERT_2|${LE_SSL_CERT_2}|g"  /etc/nginx/conf.d/default.conf 2>/dev/null
sed -i "s|SSL_CHAIN_CERT_2|${LE_SSL_CHAIN_CERT_2}|g"  /etc/nginx/conf.d/default.conf 2>/dev/null


if [ "$1" = "nginx" ]; then
    /docker-entrypoint.sh nginx

    /let-encrypt.sh wiki.jlab.ovh $LE_SSL_KEY_1 $LE_SSL_CERT_1
    /let-encrypt.sh glpi.jlab.ovh $LE_SSL_KEY_2 $LE_SSL_CERT_2
    nginx -s stop
fi
exec "$@"
----

Le scripte 'let-encrypt.sh' est appelé pour généré des certificat ssl

.fichier 'scriptes/letsencrypt.sh'
[source,shell]
----
#!/bin/sh

echo "Génération certficat ssl pour $1"
certbot --nginx -t -n -v --agree-tos --renew-by-default --email admin@jlab.ovh  -d $1
le_result=$?
if [ ${le_result} -ne 0 ]; then
    echo "failed to run certbot"
    return 1
fi

cp -fv /etc/letsencrypt/live/$1/privkey.pem $2
cp -fv /etc/letsencrypt/live/$1/fullchain.pem $3 
----

=== Configuration de nginx

==== Création du fichier 'backend-not-found.html'

Création d'un fichier html renvoyant une erreur si aucun service web n'a été trouvé.

.fichier *backend-not-found.html*
[source,html]
----
<html>
    <head>
        <title>Reverse Proxy: Not Found!</title>
    </head>
    <body>
        <h2>Reverse Proxy: Not Found!</h2>
    </body>
</html>
----

Configuration des services Web par défaut

.fichier *default.conf*
[source,conf]
----
# Service Web Wiki.
 log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

server {
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name wiki.jlab.ovh;

    # Path for SSL config/key/certificate

    ssl_certificate         SSL_CERT_1;
    ssl_certificate_key     SSL_KEY_1;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://wiki.jlab.ovh;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}

# Service Web GLPI
server {
    listen 80;
    listen 443 ssl;
    http2 on;

    server_name glpi.jlab.ovh;

    # Path for SSL config/key/certificate
    ssl_certificate         SSL_CERT_2;
    ssl_certificate_key     SSL_KEY_2;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://glpi.jlab.ovh;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}

# Default
server {
    listen 80 default_server;

    server_name _;
    root /var/www/html;

    charset UTF-8;

    error_page 404 /backend-not-found.html;
    location = /backend-not-found.html {
        allow all;
    }
    location / {
        return 404;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}
----

==== Configuration des fichiers includes/ssl.conf et includes/proxy.conf

NOTE: Plus d'info sur leurs configuration.: https://phoenixnap.com/kb/docker-nginx-reverse-proxy#ftoc-heading-11

.fichier ssl.conf
[source,conf]
----
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHAECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
ssl_prefer_server_ciphers on;

----

.fichier proxy.conf
[source,conf]
----
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_buffering off;
proxy_request_buffering off;
proxy_http_version 1.1;
proxy_intercept_errors on;
----

[NOTE]
====
Suivi tuto:
https://phoenixnap.com/kb/docker-nginx-reverse-proxy[Nginx reverse proxy sur docker]
====