= Mise en place d'un reverse proxy

L'objectif de ce proxy est d'intercepter le trafic sur le port 80, puis de les rediriger vers le bon port du service concernée en fonction de la requête HTTP, j'utiliserai pour cela nginx..

== Gestion Docker

Le proxy sera cloisonné dans un container.

== Procédure

=== Emplacement

La configuration du proxy ce trouve dans '*/srv/Web/reverse_proxy*'

Fait partie du projet github : https://github.com/docker-jb35/reverse_proxy

==== Process Clonage :

[source,shell]
----
#pensez à ajouter le clef ssh
mkdir /srv/web && cd /srv/web
git clone git@github.com:docker-jb35/reverse_proxy.git
----

=== Configuration du fichier 'Dockerfile'

Création d'un dossier "reverse_proxy" afin d'y mettre en place un fichier de configuration et d'y déployer une image nginx qui fera office de reverse-proxy

.création dossier contenant le projet reverse_proxy (nginx)
[source,shell]
----
cd /srv/web/reverse_proxy
vim /srv/web/reverse_proxy/Dockerfile
----

.fichier "DockerFile"
[source,yaml]
----
FROM nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY ./backend-not-found.html /var/www/html/backend-not-found.html

COPY ./includes/ /etc/nginx/includes/

COPY ./scriptes/entrypoint.sh /entrypoint.sh
COPY ./scriptes/let-encrypt.sh /let-encrypt.sh


ENV DEBIAN_FRONTEND=noninteractive

RUN \
    chmod +x /entrypoint.sh && \
    chmod +x /let-encrypt.sh && \
    apt update -y && apt-get install certbot python3-certbot-nginx -y 


ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "nginx", "-g", "daemon off;"  ]
----

Le fichier 'Dockerfile' copie à partir de l'image 'nginx', de plus il copie des fichiers local ayant comme destination le container 'reverse_proxy'


=== Création du fichier 'backend-not-found.html'

Création d'un fichier html renvoyant une erreur si aucun service web n'a été trouvé.

[source,html]
----
<html>
    <head>
        <title>Reverse Proxy: Not Found!</title>
    </head>
    <body>
        <h2>Reverse Proxy: Not Found!</h2>
    </body>
</html>
----

=== Création du fichier de configuration ngxinx "default.conf"

Créer le fichier *default.conf* dans le dossier *reverse_proxy*

[source,conf]
----
# Service Web Wiki.
 log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

server {
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name wiki.jlab.ovh;

    # Path for SSL config/key/certificate

    ssl_certificate         SSL_CERT_1;
    ssl_certificate_key     SSL_KEY_1;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://wiki.jlab.ovh;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}

# Service Web GLPI
server {
    listen 80;
    listen 443 ssl;
    http2 on;

    server_name glpi.jlab.ovh;

    # Path for SSL config/key/certificate
    ssl_certificate         SSL_CERT_2;
    ssl_certificate_key     SSL_KEY_2;
    
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://glpi.jlab.ovh;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}

# Default
server {
    listen 80 default_server;

    server_name _;
    root /var/www/html;

    charset UTF-8;

    error_page 404 /backend-not-found.html;
    location = /backend-not-found.html {
        allow all;
    }
    location / {
        return 404;
    }

    access_log /var/log/nginx/access.log upstream_time;
    error_log /var/log/nginx/error.log warn;
}
----

=== Mise en place du fichier 'docker-compose.yml'

Créer le fichier *docker-compose.yml* dans le dossier *reverse_proxy*

[source,yaml]
----
version: '2'
services:
  proxy:
    build: ./
    networks:
     - wiki
     - glpi
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./var/ssl:/etc/ssl/certs/nginx/
     - ./var/le:/etc/letsencrypt/
networks:
  wiki:
    external: true
    name: wiki-antora_service_web
  glpi:
    external: true
    name: glpi_glpi
----

[NOTE]
====
Suivi tuto:
https://phoenixnap.com/kb/docker-nginx-reverse-proxy[Nginx reverse proxy sur docker]
====