= Mise en place d'un reverse proxy

L'objectif de ce proxy est d'intercepter le trafic sur le port 80, puis de les rediriger vers le bon port du service concernée en fonction de la requête HTTP, j'utiliserai pour cela nginx..

== Gestion Docker

Le proxy sera cloisonné dans un container.

== Procédure

=== Emplacement

La configuration du proxy ce trouve dans '*/srv/Web/reverse_proxy*'

Fait partie du projet github : https://github.com/docker-jb35/reverse_proxy

==== Process Clonage :

[source,shell]
----
#pensez à ajouter le clef ssh
mkdir /srv/web && cd /srv/web
git clone git@github.com:docker-jb35/reverse_proxy.git
----

=== Configuration du fichier 'Dockerfile'

Création d'un dossier "reverse_proxy" afin d'y mettre en place un fichier de configuration et d'y déployer une image nginx qui fera office de reverse-proxy

.création dossier contenant le projet reverse_proxy (nginx)
[source,shell]
----
cd /srv/web/reverse_proxy
vim /srv/web/reverse_proxy/Dockerfile
----

.fichier "DockerFile"
[source,yaml]
----
FROM nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY ./backend-not-found.html /var/www/html/backend-not-found.html

COPY ./includes/ /etc/nginx/includes/

COPY ./ssl/ /etc/ssl/certs/nginx/
----

Le fichier 'Dockerfile' copie à partir de l'image 'nginx', de plus il copie des fichiers local ayant comme destination le container 'reverse_proxy'


=== Création du fichier 'backend-not-found.html'

Création d'un fichier html renvoyant une erreur si aucun service web n'a été trouvé.

[source,html]
----
<html>
    <head>
        <title>Reverse Proxy: Not Found!</title>
    </head>
    <body>
        <h2>Reverse Proxy: Not Found!</h2>
    </body>
</html>
----

=== Création du fichier de configuration ngxinx "default.conf"

Créer le fichier *default.conf* dans le dossier *reverse_proxy*

[source,conf]
----
# Service Web wiki
server {
    listen 80;
    listen 443 ssl http2;
    server_name wiki.jlab.ovh;

    # Path for SSL config/key/certificate
    ssl_certificate /etc/ssl/certs/nginx/example1.crt;
    ssl_certificate_key /etc/ssl/certs/nginx/example1.key;
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://wiki.jlab.ovh;
    }

    access_log off;
    error_log /var/log/nginx/error.log error;
}

# Service Web GLPI
server {
    listen 80;
    #listen 443 ssl http2;
    server_name glpi.jlab.ovh;

    # Path for SSL config/key/certificate
    ssl_certificate /etc/ssl/certs/nginx/example2.crt;
    ssl_certificate_key /etc/ssl/certs/nginx/example2.key;
    include /etc/nginx/includes/ssl.conf;

    location / {
        include /etc/nginx/includes/proxy.conf;
        proxy_pass http://glpi.jlab.ovh;
    }

    access_log off;
    error_log /var/log/nginx/error.log error;
}

# Default
server {
    listen 80 default_server;

    server_name _;
    root /var/www/html;

    charset UTF-8;

    error_page 404 /backend-not-found.html;
    location = /backend-not-found.html {
        allow all;
    }
    location / {
        return 404;
    }

    access_log off;
    log_not_found off;
    error_log /var/log/nginx/error.log error;
}
----

=== Mise en place du fichier 'docker-compose.yml'

Créer le fichier *docker-compose.yml* dans le dossier *reverse_proxy*

[source,yaml]
----
version: '2'
services:
  proxy:
    build: ./
    networks:
     - glpi
     - wiki
    ports:
     - 80:80
     - 443:443

networks:
  glpi:
    external: true
    name: glpi_web
  wiki:
    external: true
    name: wiki_web

----

[NOTE]
====
Suivi tuto:
https://phoenixnap.com/kb/docker-nginx-reverse-proxy[Nginx reverse proxy sur docker]
====