= Mise en place d'un reverse proxy

L'objectif de ce proxy est d'intercepter le trafic sur le port 80, puis de les rediriger vers le bon port du service concernée en fonction de la requête HTTP, j'utiliserai pour cela nginx..

== Gestion Docker

Le proxy sera cloisonné dans un container.

== Procédure

=== Configuration du fichier 'Dockerfile'

Création d'un dossier "reverse_proxy" afin d'y mettre en place un fichier de configuration et d'y déployer une image nginx qui fera office de reverse-proxy

.création dossier contenant le projet reverse_proxy (nginx)
[source,shell]
----
mkdir ~/reverse_proxy && cd ~/reverse_proxy
vim ~/reverse_proxy/Dockerfile
----

.fichier "DockerFile"
[source,yaml]
----
FROM nginx

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY ./backend-not-found.html /var/www/html/backend-not-found.html

COPY ./includes/ /etc/nginx/includes/

COPY ./ssl/ /etc/ssl/certs/nginx/
----

Le fichier 'Dockerfile' copie à partir de l'image 'nginx', de plus il copie des fichiers local ayant comme destination le container 'reverse_proxy'


=== Création du fichier 'backend-not-found.html'

Création d'un fichier html renvoyant une erreur si aucun service web n'a été trouvé.

[source,html]
----
<html>
    <head>
        <title>Reverse Proxy: Not Found!</title>
    </head>
    <body>
        <h2>Reverse Proxy: Not Found!</h2>
    </body>
</html>
----

[NOTE]
====
Suivi tuto:
https://phoenixnap.com/kb/docker-nginx-reverse-proxy[Nginx reverse proxy sur docker]
====