=  MSP 01 - Système Client (Linux)
:navtitle: Linux

== Partitionnement

découpage du disque dur `sda` en 2 partie:

* sda1 Partition lvm :  18 176 MB
* sda2 partition lvm :  le reste

[cols="^.^,^.^,^.^"]
|===
3.+| Volume Groupe (lvm)
| label | Partition  |Site (MB)
| system | sda1  | *18 176MB*
| data | sda2  | Le reste
|===

.Volume logique (system)
|===
3.+^.^| Logical Volume
^.^| label ^.^| Point de montage |Site (MB)
| racine | / | 17 Go
| boot | /boot | 512 Mo
| swap | swap | 256 Mo
|===

.Volume logique (data)
|===
3.+^.^| Logical Volume
^.^| label ^.^| Point de montage |Site (MB)
| home | /home | 1 Go
|===


== réseau

Configuration du réseau ayant pour ip : 176.16.255.254/16

[NOTE]
====
* Commande utilisé : `nmtui`
====

== Création compte utilisateur


|===
| pseudo         | mdp                    ^.^| Groupes       | Noms
|rgrimes         |	tssr@rg15_2023$	      ^.^| Direction     | Rick Grimes
|eporter  	     | tssr@ep15_2023$	     .2+^.^|  Comptabilité	| Eugene Porter
|cpeletier	     | tssr@cp15_2023$		                    | Carol Peletier (Intérimaire)
|jbrindejont	 | cldras	            .2+^.^|   Informatique	| Julie Brindejont
|nleponner	     | tssr@nl15_2023$		                       | Nicolas Le Ponner
|respinosa	     | tssr@re15_2023$	    .2+^.^| Logistique |	Rosita Espinosa
|mjones	         | tssr@mj15_2023$		                         | Morgan Jones
|ddixon	         | tssr@dd15_2023$	   .3+^.^| Commercial    | Daryl Dixon
|gstockes        |	tssr@gs15_2023$		                     | Gabriel Stokes
|mgreene	     | tssr@mg15_2023$	                         | 	Maggie Greene
|===


.Création des groupes
[source,bash]
----
groupadd direction && \
groupadd comptabiliter && \
groupadd informatique && \
groupadd logistique && \
groupadd commercial


----

.Création des utilisateurs
[source,bash]
----
useradd -c "fullname,contactPersonne,telephonetravail,téléphonedomicile,autre"
useradd -mc "Rick Grimes,,,," -g "direction" -s "/usr/bin/bash" rgrimes && \
useradd -mc "Eugene Porter,,,," -g "comptabiliter" -s "/usr/bin/bash" eporter && \
useradd -mc "Carol Peletier (Intérimaire),,,," -g "comptabiliter" -s "/usr/bin/bash" cpeletier && \
useradd -mc "Nicolas Le Ponner,,,," -g "informatique" -s "/usr/bin/ksh" nleponner && \
useradd -mc "Rosita Espinosa,,,," -g "logistique" -s "/usr/bin/bash" respinosa && \
useradd -mc "Morgan Jones,,,," -g "logistique" -s "/usr/bin/bash" mjones && \
useradd -mc "Daryl Dixon,,,," -g "commercial" -s "/usr/bin/bash" ddixon && \
useradd -mc "Gabriel Stokes,,,," -g "commercial" -s "/usr/bin/bash" gstockes && \
useradd -mc "Maggie Greene,,,," -g "commercial" -s "/usr/bin/bash" mgreene

passwd rgrimes
passwd eporter
passwd cpeletier
passwd nleponner
passwd respinosa
passwd mjones
passwd ddixon
passwd gstockes
passwd mgreene
----

/usr/bin/ksh

