= TP 5/6 Packet Tracer : 
:navtitle: titre TP 5/6

Packet Tracer - Configure Router-on-a-Stick Inter-VLAN Routing

Addressing Table
Device

Interface

IPv4 Address

Subnet Mask

Default Gateway

R1

G0/0.10

172.17.10.1

255.255.255.0

N/A

R1

G0/0.30

172.17.30.1

255.255.255.0

N/A

PC1

NIC

172.17.10.10

255.255.255.0

172.17.10.1

PC2

NIC

172.17.30.10

255.255.255.0

172.17.30.1

Objectives
Part 1: Add VLANs to a Switch

Part 2: Configure Subinterfaces

Part 3: Test Connectivity with Inter-VLAN Routing

Scenario
In this activity, you will configure VLANs and inter-VLAN routing. You will then enable trunk interfaces and verify connectivity between VLANs.

Instructions
Part 1: Add VLANs to a Switch
Step 1: Create VLANs on S1.
Create VLAN 10 and VLAN 30 on S1.

Open configuration window

Step 2: Assign VLANs to ports.
a.     Configure interfaces F0/6 and F0/11 as access ports and assign VLANs.

·         Assign the port connected to PC1 to VLAN 10.

·         Assign the port connected to PC3 to VLAN 30.

b.     Issue the show vlan brief command to verify VLAN configuration.

S1# show vlan brief

 

VLAN Name Status Ports

---- -------------------------------- --------- -------------------------------

1 default active Fa0/1, Fa0/2, Fa0/3, Fa0/4

Fa0/5, Fa0/7, Fa0/8, Fa0/9

Fa0/10, Fa0/12, Fa0/13, Fa0/14

Fa0/15, Fa0/16, Fa0/17, Fa0/18

Fa0/19, Fa0/20, Fa0/21, Fa0/22

Fa0/23, Fa0/24, Gig0/1, Gig0/2

10 VLAN0010 active Fa0/11

30 VLAN0030 active Fa0/6

1002 fddi-default active

1003 token-ring-default active

1004 fddinet-default active

1005 trnet-default active

Close configuration window

Step 3: Test connectivity between PC1 and PC3.
From PC1, ping PC3.

Question:
Were the pings successful? Why did you get this result?

Marche par car Le routeur est désactiver, les pc ne sont ni dans le même réseau; ni dans le même VLAN.

Part 2: Configure Subinterfaces
Step 1: Configure subinterfaces on R1 using the 802.1Q encapsulation.
Open configuration window

a.     Create the subinterface G0/0.10.

·         Set the encapsulation type to 802.1Q and assign VLAN 10 to the subinterface.

·         Refer to the Address Table and assign the correct IP address to the subinterface.

R1(config)# int g0/0.10

R1(config-subif)# encapsulation dot1Q 10

R1(config-subif)# ip address 172.17.10.1 255.255.255.0

b.     Repeat for the G0/0.30 subinterface.

Step 2: Verify Configuration.
a.     Use the show ip interface brief command to verify subinterface configuration. Both subinterfaces are down. Subinterfaces are virtual interfaces that are associated with a physical interface. Therefore, in order to enable subinterfaces, you must enable the physical interface that they are associated with.

b.     Enable the G0/0 interface. Verify that the subinterfaces are now active.

Close configuration window

Part 3: Test Connectivity with Inter-VLAN Routing
Step 1: Ping between PC1 and PC3.
Question:
From PC1, ping PC3. The pings should still fail. Explain.

Step 2: Enable trunking.
Open configuration window

a.     On S1, issue the show vlan command.

Question:
What VLAN is G0/1 assigned to?

b.     Because the router was configured with multiple subinterfaces assigned to different VLANs, the switch port connecting to the router must be configured as a trunk. Enable trunking on interface G0/1.

Question:
How can you determine that the interface is a trunk port using the show vlan command?

c.     Issue the show interface trunk command to verify that the interface is configured as a trunk.

Close configuration window

Step 3: Test Connectivity
If the configurations are correct, PC1 and PC3 should be able to ping their default gateways and each other.

Question:
What addresses do PC1 and PC3 use as their default gateway addresses?

end of document