= Installation Serveur SSH (Windows)

Pour installer OpenSSH avec PowerShell, exécutez PowerShell en tant qu’administrateur. Pour vous assurer qu’OpenSSH est disponible, exécutez l’applet de commande suivante :

[source,powershell]
----
Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'
----

La sortie suivante doit être retournée si aucun n’est déjà installé :

[source,powershell]
----
Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent
----

Ensuite, installez les composants serveur ou client selon vos besoins :

[source,powershell]
----
# Install the OpenSSH Client
Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

# Install the OpenSSH Server
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
----

Quel que soit le composant, la sortie suivante devrait être retournée :

[source,powershell]
----
Path          :
Online        : True
RestartNeeded : False
----


== Démarrer et configurer OpenSSH Server

Pour démarrer et configurer OpenSSH Server pour une première utilisation, ouvrez PowerShell en tant qu’administrateur, puis exécutez les commandes suivantes pour démarrer `sshd service` :

[source,powershell]
----
# Start the sshd service
Start-Service sshd

# OPTIONAL but recommended:
Set-Service -Name sshd -StartupType 'Automatic'

# Confirm the Firewall rule is configured. It should be created automatically by setup. Run the following to verify
if (!(Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue | Select-Object Name, Enabled)) {
    Write-Output "Firewall Rule 'OpenSSH-Server-In-TCP' does not exist, creating it..."
    New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
} else {
    Write-Output "Firewall rule 'OpenSSH-Server-In-TCP' has been created and exists."
}
----


== Se connecter à OpenSSH Server

Une fois l’installation terminée, vous pouvez vous connecter à OpenSSH Server à partir d’un appareil Windows 10 ou Windows Server 2019 avec OpenSSH Client installé à l’aide de PowerShell, comme suit. Veillez à exécuter PowerShell en tant qu’administrateur :

[source,powershell]
----
ssh username@servername
----

Création d'un lien symbolique de Powershell

[source,powershell]
----
cmd /D /C mklink c:\pwsh "C:\Program Files\PowerShell\7"
----



Modification de sshd_config

[source,powershell]
----
Subsystem powershell c:\pwsh\pwsh.exe -sshs -NoLogo -NoProfile
----

Redémarrage du service

[source,powershell]
----
----


== Entrer dans une session avec powershell

[source,powershell]
----
$session = New-PSSession -HostName UbuntuVM1 -UserName TestUser
Enter-PSSession $session
----