= Création Service iPXE

== Configuration Service DHCP d'un pare-feu OPNSense

****
Afin que mon routeur puissent accepté les requête DHCP pendant le démarrage de PC, ,il faut bidouiller un fichier de configuration

Ce fichier est : `/usr/local/etc/inc/plugins.inc.d/dhcpd.inc`

Voici les 2 extrait à ajouter.
[%collapsible]
====
----
$dhcpdconf .= <<<EOD

###PXE###
option space PXE;
option PXE.mtftp-ip code 1 = ip-address;
option PXE.mtftp-cport code 2 = unsigned integer 16;
option PXE.mtftp-sport code 3 = unsigned integer 16;
option PXE.mtftp-tmout code 4 = unsigned integer 8;
option PXE.mtftp-delay code 5 = unsigned integer 8;
option arch code 93 = unsigned integer 16;

option space ipxe;
option ipxe-encap-opts code 175 = encapsulate ipxe;
option ipxe.priority code 1 = signed integer 8;
option ipxe.keep-san code 8 = unsigned integer 8;
option ipxe.skip-san-boot code 9 = unsigned integer 8;
option ipxe.syslogs code 85 = string;
option ipxe.cert code 91 = string;
option ipxe.privkey code 92 = string;
option ipxe.crosscert code 93 = string;
option ipxe.no-pxedhcp code 176 = unsigned integer 8;
option ipxe.bus-id code 177 = string;
option ipxe.san-filename code 188 = string;
option ipxe.bios-drive code 189 = unsigned integer 8;
option ipxe.username code 190 = string;
option ipxe.password code 191 = string;
option ipxe.reverse-username code 192 = string;
option ipxe.reverse-password code 193 = string;
option ipxe.version code 235 = string;
option iscsi-initiator-iqn code 203 = string;
# Feature indicators
option ipxe.pxeext code 16 = unsigned integer 8;
option ipxe.iscsi code 17 = unsigned integer 8;
option ipxe.aoe code 18 = unsigned integer 8;
option ipxe.http code 19 = unsigned integer 8;
option ipxe.https code 20 = unsigned integer 8;
option ipxe.tftp code 21 = unsigned integer 8;
option ipxe.ftp code 22 = unsigned integer 8;
option ipxe.dns code 23 = unsigned integer 8;
option ipxe.bzimage code 24 = unsigned integer 8;
option ipxe.multiboot code 25 = unsigned integer 8;
option ipxe.slam code 26 = unsigned integer 8;
option ipxe.srp code 27 = unsigned integer 8;
option ipxe.nbi code 32 = unsigned integer 8;
option ipxe.pxe code 33 = unsigned integer 8;
option ipxe.elf code 34 = unsigned integer 8;
option ipxe.comboot code 35 = unsigned integer 8;
option ipxe.efi code 36 = unsigned integer 8;
option ipxe.fcoe code 37 = unsigned integer 8;
option ipxe.vlan code 38 = unsigned integer 8;
option ipxe.menu code 39 = unsigned integer 8;
option ipxe.sdi code 40 = unsigned integer 8;
option ipxe.nfs code 41 = unsigned integer 8;

EOD;
----

----



        $dhcpdconf .= <<<EOF
        ping-check = 1;
        next-server 172.15.255.250;
        if option arch = 00:07 or option arch = 00:09 {
            if exists user-class and option user-class = "iPXE" {
                    filename "http://172.15.255.250/boot.php";
            } else {
                    filename "ipxe.efi";
            }
    } else if option arch = 00:06 {
            if exists user-class and option user-class = "iPXE" {
                    filename "http://172.15.255.250/boot.php";
            } else {
                    filename "ipxe32.efi";
            }
    } else {
         if exists user-class and option user-class = "iPXE" {
                    filename "http://172.15.255.250/boot.php";
            } else {
                    filename "undionly.kpxe";
            }
    } 
EOF;
----
====
****

== Configuration Serveur Ipxe

=== Installation du serveur tftp

****
* Mon serveur tournera sour Debian 11 x64
* Programme à install `tftp-hpa`

****

[source,bash]
====
apt update -y && apt upgrade -y
apt install -y tftpd-hpa git gcc binutils liblzma-dev make
====

.Extrait Fichier configuration `/etc/default/tftpd-hpa`
----
# /etc/default/tftpd-hpa

TFTP_USERNAME="tftp"
TFTP_DIRECTORY="/srv/tftp"
TFTP_ADDRESS=":69"
TFTP_OPTIONS="--secure -v"
----

=== Construction des image Boot Ipxe

.Fichier `/tmp/ipxe/src/chain.ipxe`
----
#!ipxe

dhcp
chain http://172.16.255.250/boot.php
----

[source,bash]
====
cd /tmp
#Clonage dépot IPXE
git clone https://github.com/ipxe/ipxe.git
cd ipxe/src

#Fichier Point de départ chargement IPXE.
vim chain.ipxe
make bin-x86_64-efi/ipxe.efi EMBED=chain.ipxe && \
make bin-i386-efi/ipxe.efi EMBED=chain.ipxe && \
make bin/undionly.kpxe EMBED=chain.ipxe
cp bin-x86_64-efi/ipxe.efi /srv/tftp/ && \
cp bin/undionly.kpxe /srv/tftp/ && \
cp bin-i386-efi/ipxe.efi /srv/tftp/ipxe32.efi
====

=== Installation et configuration des services Web

[source,bash]
====

#installation Serveur Web (basique)
apt install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl php-json php-mbstring php-xml php-zip
ln -s /srv/tftp /var/www/html/tftp
====