= TP 7 (Gestion des espaces disque)
:source-highlighter: coderay

== Objectifs

Gestion des disques et des systèmes de fichiers

== Principales tâches à réaliser

=== 1. pass:[<u>Gestion des disques</u>] : sur la station avec environnement graphique

Ajouter un nouveau disque de 40 Go.
Vérifier que le disque est bien présent dans /dev

[NOTE]
====
Disque virtuel de 41 Go Crée.
====


Créer 1 partition sur le nouveau disque avec fdisk :
• Partition principale de la totalité du disque pour du LVM

[source,bash]
----
#disque détecté grace à la commande ci-dessous
echo "- - -" > /sys/class/scsi_host/host2/scan
#création d'une partition prenant tous le disque pour lvm
fdisk /dev/sdb
# -> /dev/sdb1              2048 85983231 85981184    41G 8e LVM Linux
----

Intégrer la partition au groupe de volume présent dans votre système.

.Ajout d'un volume physique pour LVM
[source,bash]
----
# Vérification des Volumes Physique
pvs

# Retour Ligne de commande
# PV         VG     Fmt  Attr PSize   PFree
# /dev/sda1  system lvm2 a--  <40,00g    0

# Intégration de /dev/sdb1 aux volumes physique gérer par LVM
pvcreate /dev/sdb1

# Vérification des Volumes Physique
pvs
# Retour Ligne de commande
# PV         VG     Fmt  Attr PSize   PFree
# /dev/sda1  system lvm2 a--  <40,00g      0
# /dev/sdb1         lvm2 ---  <41,00g <41,00g
----

.Intégration du volume physique (/dev/sdb1) au groupe : system
[source,bash]
----
vgs
# Retour Ligne de commande
# VG     #PV #LV #SN Attr   VSize   VFree
# system   1   4   0 wz--n- <40,00g    0
vgextend system /dev/sdb1

# Retour Ligne de commande
#  Volume group "system" successfully extended

vgs

# Retour Ligne de commande
# VG     #PV #LV #SN Attr   VSize  VFree
# system   2   4   0 wz--n- 80,99g <41,00g
----

On constate que le groupe de volumes à augmenter de `41 GiB`, et contiens 2 Volume Physique

Créer un volume logique de 20 Go nommé var.
Agrandir le volume logique home avec le reste de l’espace disponible du groupe de volume.

.Création volume logique 'var'
[source,bash]
----
lvcreate -L 20g -n var system
# Retour Ligne de commande
#  Logical volume "var" created.

#recap lvs
lvs

# Retour Ligne de commande
#  LV      VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
#  home    system -wi-ao---- <14,81g
#  racine  system -wi-ao----  18,62g
#  swap    system -wi-ao----  <1,91g
#  var     system -wi-a-----  20,00g
#  windows system -wi-ao----  <4,66g
----

.extension du volume 'home'
[source,bash]
----
# étendre le volume logique `home`
lvextend -l +100%FREE /dev/mapper/system-home

# Retour Ligne de commande
#  Size of logical volume system/home changed from <14,81 GiB (3791 extents) to 35,80 GiB (9166 extents).
#  Logical volume system/home successfully resized.

resize2fs /dev/mapper/system-home

# Retour Ligne de commande
#resize2fs 1.46.2 (28-Feb-2021)
#Filesystem at /dev/mapper/system-home is mounted on /home; on-line resizing required
#old_desc_blocks = 2, new_desc_blocks = 5
#The filesystem on /dev/mapper/system-home is now 9385984 (4k) blocks long.
----