= Module 02 - Configuration de l'adressage réseau
:navtitle: Adressage réseau

* Module précédent -> xref:tssr2023/module-09/MiseEnOeuvre.adoc[Module 01 - Contexte de mise en oeuvre]
* Module suivant -> xref:tssr2023/module-09/routage.adoc[Module 03 - Routage et traduction]

Notes -> xref:notes:eni-tssr:services-reseau-linux.adoc[Services Réseau Linux]

Afin qu’une communication puisse se faire entre deux postes, des liens physiques et logiques doivent exister.

Un réseau physique est matérialisé par l’ensemble des matériels mis en oeuvre afin de permettre le transfert de trames entre différents équipements.

Un réseau logique IPv4 est caractérisé par :

* Une adresse de réseau ;
* Un masque ;
* Une adresse de diffusion.

== 2.1. Elements de paramétrage

=== 2.1.1. Paramétrage d’une carte réseau

La configuration réseau d’un poste se traduit par la mise en oeuvre d’un ou plusieurs des points suivants :

* La configuration d’une adresse IP d’hôte et du masque associé (le système en déduit les adresses de réseau et de diffusion) ;
* La configuration d’une passerelle par défaut ;
* La définition d’un nom d’hôte ;
* La configuration cliente DNS.

=== 2.1.2. Nommage des cartes réseau

Le mécanisme de gestion des services systemd a introduit un schéma de nommage particulier pour les cartes réseau, il s’adapte selon les matériels détectés pour éviter les erreurs d’interprétation.

Dans le cas des machines virtuelles déployées avec VMware Workstation, il se présente la forme `ens[1-n]`.

[NOTE,caption=Info]
====
Cette évolution est apparue avec Debian 9 et Red Hat / CentOS 7.

Sur des systèmes plus anciens le nommage des cartes réseau Ethernet est sous la forme `eth[0-n]`.
====

La carte de boucle locale (loopback) est identifiée avec la forme spécifique `lo`.

== 2.2. Outils et méthodes de configuration du réseau

=== 2.2.1. Configuration depuis le service Network Manager

Si le service _Network Manager_ est installé, il est préférable de l’utiliser pour gérer la configuration réseau du poste.

[source,shell]
----
# systemctl status NetworkManager
● NetworkManager.service - Network Manager
    Loaded: loaded (/lib/systemd/system/NetworkManager.service; enabled; vendor p>
    Active: active (running) since Thu 2022-06-23 07:57:22 CEST; 1 weeks 1 days a>
----

Les actions réalisées via _Network Manager_ sont prises en compte immédiatement et durablement.

Le service _Network Manager_ peut être configuré :

* Au moyen de lignes de commandes : via la commande `nmcli` (Command Line Interface) ; 
** cette méthode est particulièrement adaptée à l’application de modification via des scripts.
* Au moyen d’une interface textuelle de configuration : via la commande `nmtui`. 
** Plus conviviale que les commandes `nmcli`, c’est une méthode qui requiert l’interaction utilisateur.
* Au moyen d’un *composant graphique* interagissant avec _Network Manager_ ; 
** cela requiert la présence d’un environnement graphique sur la machine cible. *C’est la méthode privilégiée sur les stations de travail sous GNU/Linux*.

=== 2.2.2. Configuration avec la commande ip

La commande `ip` permet de gérer la configuration réseau. Le résultat d’exécution de cette commande est pris en compte immédiatement. Cependant, sans configuration complémentaire, les modifications apportées dynamiquement par cette commande ne sont *pas conservées après redémarrage du service réseau* ou de la machine.

[source,shell]
----
Usage: ip [ OPTIONS ] OBJECT { COMMAND | help }
       ip [ -force ] -batch filename
where  OBJECT := { link | address | addrlabel | route | rule | neigh | ntable |
                   tunnel | tuntap | maddress | mroute | mrule | monitor | xfrm |
                   netns | l2tp | fou | macsec | tcp_metrics | token | netconf | ila |
                   vrf | sr | nexthop | mptcp }
       OPTIONS := { -V[ersion] | -s[tatistics] | -d[etails] | -r[esolve] |
                    -h[uman-readable] | -iec | -j[son] | -p[retty] |
                    -f[amily] { inet | inet6 | mpls | bridge | link } |
                    -4 | -6 | -I | -D | -M | -B | -0 |
                    -l[oops] { maximum-addr-flush-attempts } | -br[ief] |
                    -o[neline] | -t[imestamp] | -ts[hort] | -b[atch] [filename] |
                    -rc[vbuf] [size] | -n[etns] name | -N[umeric] | -a[ll] |
                    -c[olor]}
----

Pour utiliser cette commande, on indique le type d’objet à manipuler suivi de la commande `[ + arguments ]` à lui appliquer.

Les commandes disponibles dépendent des objets concernés. Des sections d’aide propres aux différents objets sont utiles pour lister les commandes disponibles pour le contexte concerné.

[source,shell]
----
$ man ip
$ man ip-address
----

=== 2.2.3. Configuration durable dans le fichier interfaces

IMPORTANT: Seules les cartes réseau *non configurées via Network Manager* sont à configurer dans le fichier de configuration des interfaces présenté ci-dessous.


Sur un serveur ne disposant pas d’interface graphique, la configuration du réseau passera par la modification du fichier `/etc/network/*interfaces*`. Après toute modification de ce fichier, il est nécessaire de redémarrer le service `networking` pour leur prise en compte.

[source,shell]
----
# systemctl stop networking
# systemctl start networking
----

== 2.3. Configurer le réseau

=== 2.3.1. Configuration de l’adressage IP

==== Configuration du Network-Manager

Des commandes `nmcli` sont présentées ci-dessous pour la configuration via le _Network Manager_.

Bien que non présentées dans ce support, des commandes `nmtui` ou le composant graphique de gestion peuvent aussi être utilisés.

.Affichage de la configuration des interfaces :
[source,shell]
----
$ nmcli
ens33: connecté à Connexion filaire 1
    "Intel 82545EM"
    ethernet (e1000), 00:0C:29:4C:A4:AC, hw, mtu 1500
    ip4 par défaut
    inet4 10.14.200.34/16
    route4 0.0.0.0/0
    route4 10.14.0.0/16
    inet6 fe80::cf04:9afa:a39d:a810/64
    route6 fe80::/64
    route6 ff00::/8

lo: non-géré
    "lo"
    loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536

DNS configuration:
    servers: 10.0.0.3 10.35.0.3
    domains: ad.campus-eni.fr
    interface: ens33
----

.Modification immédiate et durable de l’adresse IP :
[source,shell]
----
# nmcli connection modify Wired\ connection\ 1 ipv4.addresses 192.168.66.6/24
# nmcli connection modify Wired\ connection\ 1 ipv4.addresses 192.168.66.6/24
ipv4.method manual
# nmcli connection modify Wired\ connection\ 1 +ipv4.addresses 192.168.1.1/24 ①
----

① Ajoute une adresse à l’interface existante. Le signe `-` permet au contraire de supprimer l’adresse.

.Modification temporaire (immédiate mais non durable) de l’adresse IP :
[source,shell]
----
# nmcli device modify ens33 ipv4.addresses 192.168.200.150/24 ipv4.method manual ①
----

① La dernière partie désactive le DHCP

==== Configuration avec la commande `IP`

.Affichage de la configuration des interfaces : état d’activation, adressage physique et IP
[source,shell]
----
# ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
        valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
        valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:c0:5a:67 brd ff:ff:ff:ff:ff:ff
    altname enp2s1
    inet 10.14.200.33/16 brd 10.14.255.255 scope global dynamic ens33
        valid_lft 171960sec preferred_lft 171960sec
    inet6 fe80::20c:29ff:fec0:5a67/64 scope link
        valid_lft forever preferred_lft forever
----

[source,shell]
----
# ip address add 10.11.12.13/24 dev ens33 ①
# ip address del 172.16.0.1/16 dev ens37 ②
# ip address flush ens33 ③
----

[none]
* ① Ajout d’adresse
* ② suppression d’une adresse
* ③ suppression de toutes les adresses d’une interface

.Activer / désactiver une interface :
[source,shell]
----
# ip link set ens33 down
# ip link set ens37 up
----

==== Configuration dans le fichier `interfaces`

.Exemple 1. configuration de l’adressage de deux cartes dans le fichier de configuration des interfaces : `/etc/network/*interfaces*`
====
[source,shell]
----
# L'interface réseau de loopback => il ne faut pas la modifier
auto lo
iface lo inet loopback

# L'interface ens33 est configurée manuellement.
auto ens33 ①
iface ens33 inet static
    address 192.168.66.6 ②
    netmask 255.255.0.0

# L'interface ens37 est quant à elle configurée via DHCP.
auto ens37
iface ens37 inet dhcp
----

[none]
* ① Auto permet un renouvellement automatique s’il y a un changement au redémarrage du service.
* ② L’indentation n’est pas significative, mais aide à s’organiser.

====

=== 2.3.2. Configuration de la passerelle par défaut

==== Configuration du _Network-Manager_

Ajout ou modification de l’adresse de la passerelle par défaut :

[source,shell]
----
# nmcli connection modify Wired\ connection\ 1 ipv4.gateway 192.168.66.254
----

==== Configuration avec la commande `ip`

Afin de visualiser ou modifier la table de routage, nous utiliserons l’objet `route` de la commande `ip`.

[source,shell]
----
$ man ip-route
----

.Affichage de la table de routage : itinéraires et passerelles :
[source,shell]
----
$ ip route
default via 192.168.0.254 dev ens37
10.11.0.0/16 dev ens33 proto kernel scope link src 10.11.12.13
192.168.0.0/24 dev ens37 proto kernel scope link src 192.168.0.1
----

.Ajouter une route par défaut :
[source,shell]
----
# ip route add default via 10.11.0.254
----


.Modifier la route par défaut :
[source,shell]
----
# ip route change default via 10.11.255.254
----

.Supprimer la route par défaut :
[source,shell]
----
# ip route del default via 192.168.0.254
----

==== Configuration dans le fichier interfaces

La directive gateway permet de définir la passerelle par défaut dans le fichier `/etc/network/*interfaces*`.

[source,shell]
----
# L'interface ens33 est configurée manuellement.
auto ens33
iface ens33 inet static
    address 192.168.66.6
    netmask 255.255.0.0
    gateway 192.168.66.254
----


== 2.4. Configuration du nom d’hôte

Le nom d’hôte peut être un nom court, ou un nom FQDN (Fully Qualified Domain Name) séparé par des points. La commande hostname affiche le nom de la machine et permet de le modifier dynamiquement. Celui-ci est configuré dans le fichier `/etc/hostname`, qui ne doit contenir que le nom de la machine :

[source,shell]
----
srv-lan.demo.eni
----

Il est possible de modifier le nom d’hôte au moyen de la commande `nmcli` suivante :

[source,shell]
----
# nmcli general hostname srv-lan.demo.eni
----

Attention, le nom d’hôte doit être résolu localement ; en cas de changement il faut également modifier le fichier de correspondances local `/etc/hosts`.

[source,shell]
----
127.0.0.1 localhost
127.0.1.1 srv-lan.demo.eni srv-lan
----

== 2.5. Paramétrage client DNS

Pour que les postes soient en mesure de résoudre des noms d’hôtes en adresses IP, le service DNS est généralement utilisé. Le ou les adresses IP des serveurs interrogés doivent être renseignées dans les paramétrages réseau du poste.

=== 2.5.1. Configuration de l’ordre de résolution

La liste ordonnancée des mécanismes utilisés pour la résolution de noms est inscrite derrière la directive hosts du fichier `/etc/nsswitch.conf`

[source,shell]
----
$ grep hosts /etc/nsswitch.conf
hosts: files dns
----

Dans l’exemple présenté ci-dessus, les mécanismes suivants sont utilisés successivement :

1. `files` : lecture de fichier `/etc/hosts`
2. `dns` : interrogation du serveur DNS configuré sur le poste

Dans le cas où un *environnement graphique* a été installé, le paquet avahi-daemon est également fourni. Il fournit des méthodes pour faciliter la résolution locale et un cache DNS.

La directive `hosts` du fichier `/etc/nsswitch.conf` aura le contenu suivant :

[source,shell]
----
$ grep hosts /etc/nsswitch.conf
hosts: files mdns4_minimal [NOTFOUND=return] dns myhostname
----

Dans ce cas, les mécanismes utilisés sont :

1. `files` : lecture de fichier `/etc/hosts`
2. `mdns4_minimal` : interrogation mDNS (multicast DNS) pour les noms d’hôtes IPv4 en `.local`
3. `dns` : interrogation du serveur DNS configuré sur le poste
4. `myhostname` : résolution des noms locaux du poste

=== 2.5.2. Configuration du serveur DNS interrogé

Si `dns` fait partie des services référencés dans ce fichier `/etc/nsswitch.conf`, le ou les serveurs DNS à interroger sont alors à configurer.

==== Configuration du Network-Manager

Ajout ou modification de l’adresse du serveur DNS :

[source,shell]
----
# nmcli connection modify Wired\ connection\ 1 ipv4.dns 192.168.66.1
----

Pour déclarer plusieurs adresses de serveur, indiquer leurs adresses IP en séparant par une virgule.

==== Configuration dans le fichier `*resolv.conf*`

En l’absence du Network-Manager, on configure directement les paramètres DNS dans le fichier `/etc/resolv.conf`

[source,shell]
----
search demo.eni ad.campus-eni.fr
domain ad.campus-eni.fr
nameserver 10.0.0.3
nameserver 10.100.0.3
----

Les directives `nameserver` indiquent les adresses de serveurs DNS à requêter. Seul en cas d’indisponibilité du premier, le suivant sera sollicité.

Les directives `search` et `domain` permettent de définir une liste de suffixes DNS.

Dans le cas d’une interface réseau configurée en DHCP, les paramètres sont renseignés automatiquement à partir des informations fournies par le serveur DHCP.

== TP 01 - Mise en oeuvre et configuration réseau IPv4 de l'environnement