= Découverte du cours

* Point suivant -> xref:Formation1/presentation/ressources-participants.adoc[Ressources pour les participants]

xref:Formation1/index.adoc[Retour Récapitulatif Formation]

== Bienvenue

Bienvenue dans la formation *IT Essentials version 7.0* . Cette formation couvre les notions fondamentales du matériel et des logiciels des ordinateurs, ainsi que des concepts avancés tels que la sécurité, la mise en réseau et les responsabilités d'un professionnel de l'informatique.

Ces supports de cours vous aideront à développer les compétences nécessaires pour :

* Choisir les composants informatiques appropriés pour assembler, réparer ou mettre à niveau des ordinateurs personnels.
* Expliquer comment utiliser correctement les outils et travailler en toute sécurité dans un atelier.
* Installer des composants pour assembler, réparer ou mettre à niveau des ordinateurs personnels.
* Expliquer les procédures de maintenance préventive et de dépannage sur les ordinateurs personnels.
* Installer des systèmes d'exploitation Windows.
* Assurer la gestion et la maintenance des systèmes d'exploitation Windows.
* Configurer les ordinateurs afin qu'ils communiquent sur un réseau.
* Configurer des périphériques pour qu'ils se connectent à Internet et aux services cloud.
* Expliquer comment utiliser, configurer et gérer des ordinateurs portables et des appareils mobiles.
* Décrire les procédures de configuration, de sécurisation et de dépannage des systèmes d'exploitation mobiles, macOS et Linux.
* Installer et partager une imprimante de manière à ce qu'elle réponde aux exigences définies.
* Mettre en œuvre la sécurité de base du réseau, de l'hôte et des données.
* Expliquer les rôles et les responsabilités du professionnel de l'IT.