= Module 05 - Arborescence Unix - Linux
:navtitle: Arborescence Unix - Linux


* Module précédent -> xref:tssr2023/module-03/aide.adoc[Module 04 - À l'aide]
* Module suivant -> xref:tssr2023/module-03/shell.adoc[Module 05 - Le Shell]

Notes -> xref:notes:eni-tssr:client-linux.adoc[Client Linux]

La structure du système de fichiers (FS) est arborescente (imbrication de répertoires), le chemin d'accès à un fichier permet de spécifier la position exacte de ce fichier dans l'arborescence. 

== Les FHS

Le FHS est maintenu par le *Free Standards Group*. Il a été créé à partir de 1993 pour homogénéiser les arborescences des différents UNIX et Linux. Le FHS définit l'arborescence et le contenu des principaux répertoires des systèmes de fichiers des systèmes d'exploitation GNU/Linux et de la plupart des systèmes UNIX. Elle est actuellement maintenue par la Linux Fondation, la dernière version date de juin 2015 et porte le numéro de version 3.0.

Malheureusement, beaucoup de distributions GNU/Linux ne respectent pas à la lettre le standard, même celles développées par des membres du Free Standards Group. De surcroît, plusieurs versions d’UNIX ont conservé une arborescence complètement différente. 

Malgré cela, il est indéniable que le rapprochement des hiérarchies de systèmes de fichiers permet une approche plus simple entre les différents systèmes UNIX ou GNU/Linux et facilite le travail des administrateurs système. 
[cols="10,~"]
|===
^.^h| Répertoire ^.^h| Description
| /bin | Commandes de base nécessaires au démarrage et à l’utilisation minimale du système pour tous les utilisateurs (peut être un lien symbolique vers /usr/bin). 
| /boot | Répertoire pour le chargeur d’amorçage et fichiers nécessaires au lancement du noyau. 
| /dev | Fichiers de périphériques physiques (disque dur, etc.) ou virtuels (/dev/null /dev/zero …). 
| /etc | Fichiers de configuration du système. C’est l’abréviation de : editable text configuration. 
| /home | Répertoire d'accueil des utilisateurs. 
| /lib | Bibliothèques principales utilisées par les commandes de /bin et /sbin (peut être un lien symbolique vers /usr/lib
| /lost+found | Fichiers récupérés par la commande fsck (pas forcément présent). 
| /media | Point de montage des périphériques de stockage amovibles (automatique). 
| /mnt | Point de montage pour les montages temporaires (manuel). 
| /opt | Répertoire pour l’installation d’applications tierces. 
| /proc | Système de fichiers virtuel reflétant l’état du noyau et les différents processus.
| /sys | Système de fichiers virtuel reflétant l’état du matériel. 
| /root | Répertoire d'accueil de l'utilisateur root. 
| /sbin | Exécutables système pour les administrateurs (peut être un lien symbolique vers /usr/sbin). 
| /srv | Données pour les services hébergés par le système (peu utilisé). 
| /tmp | Fichiers temporaires (il est généralement vidé après un reboot). 
| /usr 
a| Acronyme de : UNIX System Ressources. Il contient certains répertoires présents à la racine, mais qui ne sont pas nécessaires au fonctionnement minimal du système. 
****
* /usr/bin  : Binaires non indispensables à un système minimal. 
* /usr/lib : Bibliothèques. 
* /usr/sbin : Binaires d’administration. 
* /usr/share : Fichiers indépendants de la plateforme. Exemples : pages man, fonds d’écran,
* thèmes d’interface, etc... 
****
| /var | Fichiers de taille variable (journaux, base de données etc.). 
|===

== Chemin absolu vs chemin relatif

Lorsque le chemin commence par le caractère `/`, il est donné depuis la racine : on parle alors de chemin absolu. 

Sinon, le chemin est fourni par rapport au répertoire courant : on parle dans ce cas de chemin relatif. 

Si le chemin d'accès (absolu ou relatif) d’un fichier est composé d'un ou plusieurs répertoires, le caractère / sépare les différents niveaux. 

== Répertoire parent et répertoire courant

Chaque répertoire, en dehors de la racine, contient au minimum deux sous-répertoires particuliers : 

* `..` Le répertoire parent 
* `.` Le répertoire courant 

Il peut être judicieux, dans certains cas, de remonter dans l'arborescence plutôt que de descendre. Dans ce cas, le nom de chemin contiendra "`..`" pour se positionner dans le répertoire de niveau immédiatement supérieur à celui dans lequel on est positionné. 

== Les types de fichiers

=== Sous Unix, tout est fichier

L'utilisateur perçoit les fichiers comme rangés dans des répertoires, eux-mêmes classés dans d'autres répertoires, cela nous permet d'avoir une vision hiérarchique de l'organisation des fichiers et d'en faciliter la gestion. 

Le système d'exploitation en a, lui, une tout autre vision. Pour lui, un fichier est un ensemble de données écrites sur le support de stockage, sans aucune notion hiérarchique, mais accessible par un inode qui possède des pointeurs vers ses données. 

Pour UNIX, un écran, la souris ou un disque dur sont représentés par des fichiers, tout comme les processus. 

=== Quatre principaux types de fichiers

==== Fichiers ordinaires

Les fichiers ordinaires sont tous, des fichiers dans le sens usuel du terme, ainsi, les textes, les scripts, les commandes sont des fichiers ordinaires.

==== Répertoires

Le répertoire est pour le système un type de fichier particulier, contenant les références permettant d'accéder à des fichiers. 

==== Fichiers spéciaux

Les fichiers spéciaux désignent les périphériques matériels de la machine. 

Ils sont subdivisés en deux parties : 

* Les fichiers spéciaux en mode bloc qui concernent les périphériques de stockage
* Les fichiers spéciaux en mode caractère ou raw qui eux représentent les périphériques d'entrées/sorties comme le clavier, la souris ou l'écran.

==== Liens symboliques

Un lien symbolique est un fichier spécial qui permet de pointer vers un nom de fichier. Il permet de simplifier les accès aux fichiers et répertoires et à maintenir la compatibilité entre systèmes UNIX. 

== Qu'est-ce qu'un inode ?

Les *inodes* contiennent des informations concernant les fichiers stockés sur les systèmes de fichiers. Ils sont référencés par des numéros.

Lorsqu'un utilisateur tente d'accéder à un fichier, l'inode du fichier est lu. Si les permissions autorisent l'accès au fichier, les données seront accessibles grâce aux pointeurs. 

L'inode contient des informations telles que : 

* L'identifiant de l'utilisateur propriétaire du fichier ; 
* L'identifiant du groupe propriétaire du fichier ; 
* Les permissions d'accès au fichier ; 
* Les dates de dernière modification, de dernier accès et de dernière modification de l'inode ; La taille du fichier ; 
* Le nombre de liens du fichier (nous y reviendrons) ; 
* Le type de fichier (ordinaire, répertoire, lien symbolique etc.) ; 
* Les pointeurs qui permettent d'accéder physiquement aux données du fichier. 

IMPORTANT: *l'inode ne contient pas le nom du fichier *

== Manipuler les fichiers

La gestion des fichiers implique de respecter des règles dans la désignation des fichiers. 

=== Pas de notion d'extension

Les noyaux des systèmes UNIX ne gèrent pas la notion d'extensions de fichier comme Windows. Ainsi, le fait d'appeler un fichier fic.txt ou programme.exe n'indique en rien au système que nous avons à faire à un fichier texte ou à une application. L'utilisation des extensions sera donc uniquement utile à l'utilisateur, pour reconnaître les types de fichiers. 

=== Caractères interdits

Hormis le slash `/` qui est le séparateur dans l'arborescence, il n'y a pas de caractères interdits pour le nommage des fichiers. Il faudra malgré tout prendre garde aux caractères spéciaux qui peuvent être difficiles à manipuler. 

=== Gestion de la classe

Attention à la casse, `fichier.txt`, `Fichier.txt` et `FICHIER.TXT` sont trois fichiers différents. 

=== Les fichiers cachés

Les fichiers qui commencent par un point "`.`" sont considérés comme "cachés" par certaines commandes et par les gestionnaires de fichiers graphiques. Les fichiers de configuration des environnements utilisateurs contiennent souvent de tels fichiers. 

=== Longueur des nomes de fichiers

Les noms de fichiers peuvent atteindre 255 caractères. 

== Pwd : Affiche le chemin du répertoire courant

|===
^.^| Syntaxe : `*pwd*`
|===

La commande `pwd` affiche le répertoire courant, c'est-à-dire le répertoire dans lequel l'utilisateur se trouve au moment de l'exécution de la commande. 

C'est une des rares commandes sans option ni argument. 

.Exemple : 
[source,shell]
----
$ pwd 
/home/benoit 
----

== CD : Changement de répertoire

|===
^.^| Syntaxe : `*cd* <chemin>`
|===

****
* `Chemin` ->  Le chemin du répertoire dans lequel on veut se positionner. 
****

Sans indication du chemin, la commande cd permet de se positionner automatiquement dans le répertoire de connexion. 

.Exemples :
[source,shell]
----
$ pwd 
/home/Tom 

$ cd /var/log 
$ pwd 
/var/log

$ cd ../spool 
$ pwd 
/var/spool

$ cd
$ pwd
/home/Tom 

$ cd -
$ pwd
/var/spool
----

== Mkdir : Création de répertoire

|===
^.^| Syntaxe : `*mkdir* [options] <monrep>`
|===


****
* `-m mode` -> valeur numérique permettant de fixer les permissions du répertoire si nécessaire.
* `-p`      -> Création des répertoires parents inexistants (si monrep est un chemin). 
* `monrep`  -> Nom du répertoire ou du chemin à créer. 
****

.Exemple
[source,shell]
----
$ mkdir ./Rennes/Procedures/ 
mkdir: cannot create directory './Rennes/Procedures/': No such file or directory 

$ mkdir -p ./Rennes/Procedures/ 
$ ls -l ./Rennes/ 
drwxr-xr-x 2 Tom Tom 4096 2011-01-19 02:22 Procedures 
----

== Ls : Liste de fichiers

|===
^.^| Syntaxe : `*ls* [options] <répertoire(s) ou fichier(s) ou les deux..> `
|=== 

****
* `-a` -> liste de tous les fichiers, y compris les fichiers dont le nom commence par "." répertoires père et courant inclus. 
* `-A` -> liste de tous les fichiers, y compris les fichiers dont le nom commence par "." sauf les répertoires père et courant. 
* `-C` -> présentation en colonnes avec tri vertical. 
* `-d` -> liste les répertoires eux-mêmes et pas leur contenu. 
* `-F` -> présentation en colonnes avec tri vertical, certains noms sont suivis d'un caractère indiquant le type : `/` pour un répertoire, `*` pour un fichier exécutable et `@` pour un lien symbolique
* `-i` -> affiche le numéro d'inode. 
* `-l` -> affichage au format long : type et permissions, nombre de liens physiques, utilisateur propriétaire, groupe propriétaire, taille (en octets) pour un fichier, date de dernière modification et nom du fichier ou répertoire. 
* `-m` -> présentation sous forme de liste de noms séparés les uns des autres par ",".
* `-r` -> affichage des noms avec tri inversé. 
* `-R` -> liste récursive de tous les sous-répertoires. 
* `-s` -> affiche la taille en blocs des fichiers (1 bloc = 512 octets). 
* `-t` -> tri par date de dernière modification. 
* `-u` -> tri par date de dernier accès. 
* `-x` -> présentation en colonnes avec tri horizontal. 
* `répertoire` -> nom du répertoire dont on souhaite visualiser le contenu. 
* `fichier` ->nom du ou des fichiers concernés par la liste. 
****

La commande `ls` permet de lister les noms (et caractéristiques) d'un fichier ou d'un ensemble de fichiers. Par défaut, les noms de fichiers sont affichés par ordre alphabétique. 
Les arguments répertoire et fichier peuvent contenir des métacaractères. Si aucun argument n'est spécifié à la commande `ls`, cette commande liste le contenu du répertoire courant. 

[source, shell]
----
# ls -l /etc 
-rw-r--r-- 1 root root       1467 2010-02-25 23:55 passwd 
drwxr-xr-x 4 root root       4096 2009-10-30 13:56 perl 
----

// Tableau 1
[cols="~,~,~,~,~,~,~"]
|===
//Tab 1 : ligne 1 (fusion d'une cellule sur l'ensemble de la ligne)
7.+^.^h| Décortication retour commande ci-dessus
//Tab 1 : ligne 2 chaque cellule centré horizontalement et verticalement
^.^| 1          ^.^| 2 ^.^| 3    ^.^| 4     ^.^| 5    ^.^| 6            ^.^| 7
//Tab 1Ligne 3 : colonne 1 (la cellule contient un tableau)
^.^a| 
//Tableau 1.1
[frame=none, grid=none]
!===
//Tab 1.1 : ligne 1
^.^! -rw-r--r-- 
// Tab 1.1 : ligne 2 contient de nouveau un tableau
^.^a! 
// Tableau 1.1.1 (4 colonnes, 2 lignes)
[frame=none, grid=none, cols="^.^,^.^, ^.^, ^.^"]
:===
// Tab 1.1.1 : ligne 1
 - : rw- : rw- : rw-
// Tab 1.1.1 : ligne 2
 c1(-) : c2(rw-) : c3(rw-) : c4(rw-)
:===
// Fin tableau 1.1.1
!===
// Fin tableau 1.1
//Tab 1 : Ligne 3 : colonne 2 à 7
^.^| 4 ^.^| root ^.^| root ^.^| 4096 ^.^| 2009-10-30 13:56 ^.^| perl
|===
// Fin tableau 1


// Tableau 2
[cols="^.^2h,~"]
|===
2.+^.^h| Détails des colonnes
| 1 a| 
[cols="~,~", frame=none]
!===
! c1(-) ! Ensemble de 10 caractères indiquant le *type du fichier* 
! c2(rw-) ! Les *permissions* sur ce fichier pour l'user
! c3(rw-) ! Les *permissions* sur ce fichier pour le groupe
! c4(rw-) ! Les *permissions* sur ce fichier pour les autres
2.+a! 
.Type de fichiers :
****
* `-`  -> fichier ordinaire
* `d`  -> répertoire
* `b`  -> périphérique de type bloc
* `c`  -> périphérique de type caractère
* `l`  -> lien symbolique
* `p`  -> tube nommé (FIFO)
* `s`  -> socket UNIX
****

.permissions
****
* `-`   -> pas de droit toutes positions
* `r`   -> droit de lecture première position
* `w`   -> droit d'écriture deuxième position
* `x`   -> droit d'exécution troisième position 
****
!===
| 2 | Nombre de liens physiques pour un fichier, nombre de sous-répertoires (+ 2) pour un répertoire
| 3 | Nom de l’utilisateur propriétaire 
| 4 | Nom du groupe propriétaire 
| 5 | Taille en octets pour un fichier 
| 6 | Heure et/ou date de dernière modification 
| 7 | Nom du fichier ou du répertoire 
|===

== Touch : Créer ou modifier l'horodatage de fichiers

|===
^.^| Syntaxe : `*touch* [options] <fichier> `
|=== 

Si les systèmes Windows ou Netware s'appuient sur un attribut "archive" pour réaliser des sauvegardes différentielles ou incrémentales, les systèmes UNIX ne possèdent pas d'attribut permettant de savoir si un fichier doit être sauvegardé ou non. 

Pour cela on utilise en général la date de dernière modification du fichier. Lors d'une sauvegarde complète ou incrémentale, il suffit d'utiliser un fichier de référence horodaté à une date voulue, et d'effectuer la sauvegarde des fichiers en fonction de la date de référence. 

La commande `touch` crée un fichier lorsque le fichier mentionné n'existe pas, ce qui est très pratique pour réaliser des exercices sur des fichiers

Nous ne rentrerons pas dans le détail de la commande `touch`, car la principale utilisation que nous en aurons est celle permettant la création de fichiers vides. 

Cette commande change la date de modification du fichier ou crée le fichier (vide) s'il n'existe pas : 

[source,shell]
----
$ touch test.fic 
----

À noter que la date de dernier accès, ainsi que la date de changement de l'inode sont également modifiées lors d'une modification du contenu du fichier. 

Vérifier les changements : 

[source,shell]
----
$ ls -l test.fic 
----

Une autre commande, plus riche, mais pas toujours présente : 

[source,shell]
----
$ stat test.fic  
----

== Cp : Copie de fichiers

|===
^.^| Syntaxe : `*cp* [options] <fichier_source> <fichier_cible ou répertoire cible>`
^.^| `*cp* [options] <fichiers_sources> <répertoire_source>… <répertoire_cible> `
|=== 

Si la commande possède une seule source et qu’il s’agit d’un fichier ordinaire, alors la cible peut être un fichier ou un répertoire. 

Si la commande référence plusieurs sources (fichiers ou répertoire), alors la cible ne peut être qu’un répertoire. 

Les noms de fichiers et répertoires peuvent être des chemins absolus ou relatifs. 

.Exemples : 
[source,shell]
----
$ ls -l 
-rw-r--r-- 1 Tom Tom 78 2011-05-08 00:26 tel_2005.txt

$ cp tel_2005.txt tel_2010.txt 
$ ls -l 
-rw-r--r-- 1 Tom Tom 78 2011-05-08 00:26 tel_2005.txt
-rw-r--r-- 1 Tom Tom 78 2011-05-08 05:04 tel_2010.txt

$ cp tel_2005.txt tel_2010.txt /data/listings/tel/ 
$ ls -l /data/listings/tel 
-rw-r--r-- 1 Tom Tom 78 2011-05-14 00:26 tel_2005.txt
-rw-r--r-- 1 Tom Tom 78 2011-05-14 05:04 tel_2010.txt
----


== Rm : Suppression de fichiers ou de répertoires

|===
^.^| Syntaxe : `*ls* [options] <répertoire(s) ou fichier(s) ou les deux..> `
|=== 