= Module 09 - Commandes de recherches
:navtitle: Commandes de recherches


* Module précédent -> xref:tssr2023/module-03/gestion-lien.adoc[Module 08 - Gestion des liens]
* Module suivant -> xref:tssr2023/module-03/cmd-recherches.adoc[Module 07 - Afficher du texte]

Notes -> xref:notes:eni-tssr:client-linux.adoc[Client Linux]

== Les Expressions régulières

=== Introduction aux expressions régulières

Une expression régulière est un modèle de chaînes de caractères auquel peut être associé un certain nombre de chaînes de caractères avec des caractéristiques communes : celles de l'expression régulière. 

Une expression régulière est construite à l'aide de différents caractères dont certains ont une signification particulière. Ce sont les caractères spéciaux (nommés aussi pass:[<u>atomes</u>]). 

Les expressions régulières sont utilisées par les outils d'édition et de recherche dans les fichiers tels que *vi*, *grep*, *sed*, *awk*, *ed*, *ex*, et autres. 

Il existe plusieurs versions d’expressions régulières. Nous verrons uniquement la version basique. 

Les atomes dans les expressions régulières sont des caractères générant une interprétation spécifique par l’application utilisant les expressions régulières. 

Les atomes d’expression régulière auront cette syntaxe : `*atome*`. 

Les caractères « normaux » celle-ci : `caractère`. 

==== Quantificateurs

Un atome quantificateur est un atome générant un comportement sur le caractère ou l’atome le précédant. 

.quantificateur
****
[grid=none,frame=none,cols="20,~,~"]
|===
//ligne 1
1.2+a| * `*` | -> |  Répétition du caractère qui précède de 0 à n fois
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `a*` ! Correspond à : `<rien>` ou `a` ou `aa` ou `aaa` …
!===
//ligne 2
1.2+a| * `\+` | -> |  Répétition du caractère qui le précède de 1 à n fois 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `a\+` ! Correspond à : `a` ou `aa` ou `aaa` …
!===
//ligne 3
1.2+a| * `\?` | -> |  Correspond à 0 ou 1 fois le caractère précédent 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `a\?` ! Correspond à : `<rien>` ou `a`.
!===
//ligne 4
1.2+a| * `car\{m,M\}` | -> |  Un caractère répété au minimum _m_ fois et au maximum _M_ fois 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `ab\{1,3\}c` ! Correspond à : `abc` ou `abbc` ou `abbbc` 
!===
//ligne 5
1.2+a| * `car\{n,\}` | -> |   Un caractère répété au minimum _m_ fois 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `es\{2,\}ai` ! Correspond à : essai, mais aussi à `esssai`, `essssai` … 
!===
//ligne 6
1.2+a| * `car\{n\}` | -> |  Un caractère répété _n_ fois exactement 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `[A-Z]\{3\}` ! Correspond à une chaîne de caractères composée de 3 majuscules 
!===
|===
****

==== Atomes

****
[grid=none,frame=none,cols="25,~,~"]
|===
1.4+a| * `*.*` | -> | Un caractère quelconque
                       2.+|  Par exemple : 
                       2.+| `.` peut-être `a` `b` `c` `d` `ù` `3` etc.
                       2.+| `.*` correspond à une séquence de caractères quelconques : `<rien>` ou une suite d'un nombre quelconque de n'importe quel caractère 
1.2+a| * `*[liste, car]*` | -> | 1 seul caractère parmi ceux de la liste entre `[ ]`
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*[abc12]*` ! Correspond à : `a` ou `b` ou `c` ou `1` ou `2` 
!===
1.2+a| * `*[intervalle-caractères] [car. Début - car. Fin]*` | -> |  1 seul caractère dans l'intervalle 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*[A-Z]*` ! Correspond à une lettre majuscule 
a! `*[A-Za-z]*` ! Correspond à toutes les lettres minuscules et majuscules 
a! `*[a-h15]*` ! Correspond à un caractère `a` ou `b` ou `c` … ou `h` ou `1` ou `5` 
a! `*[h-m][08]*` ! Correspond à `h0` ou `h8` ou `i0` ou `i8` ... ou `m0` ou `m8` 
!===
1.2+a| * `*[^caractères]*` | -> | 1 seul caractère autre que ceux entre `*[]*` l’atome `*^*` dans les `*[]*` est la négation 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*[^abc]*` ! Correspond à un caractère autre que `a` , `b` et `c` 
!===
1.2+a| * `*^chaîne*` | -> a| Chaîne de caractères placée en pass:[<u>début</u>] de ligne
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*^B*`  ! Une ligne qui commence par `B` 
a! `*^[aA\t]*`  ! Une ligne qui commence par `a` ou `A` ou par une `tabulation` 
a! `*^[ \t]**`  ! Une ligne qui commence par `*espace*` ou `*tabulation*` répétée de 0 à _n_ fois 
!===
1.2+a| * `*chaîne$*` | -> | Chaîne de caractères placée en pass:[<u>fin</u>] de ligne
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*fin$*`  ! Une ligne qui se termine par `fin` 
a! `*[^xyz]$*`  ! Une ligne qui se termine par n'importe quel caractère autre que `x`, `y` ou `z`
a! `*^$*`  ! Une ligne vide 
a! `*^.*$*`  ! La totalité de la ligne quel que soit son contenu 
!===
|===
****

==== Classes de caractères

Les classes de caractères sont des regroupements thématiques de caractères. 

****
[grid=none,frame=none,cols="15,~,~"]
|===
a| * `*[:alpha:]*` | -> | Des lettres 
a| * `*[:upper:]*` | -> | Des majuscules 
a| * `*[:lower:]*` | -> | Des minuscules 
a| * `*[:digit:]*` | -> | Des chiffres décimaux 
a| * `*[:xdigit:]*` | -> | Des chiffres hexadécimaux 
a| * `*[:alnum:]*` | -> | Alphanumériques 
a| * `*[:blank:]*` | -> | Espaces ou tabulations
a| * `*[:space:]*` | -> | Espaces 
a| * `*[:punct:]*` | -> | Des caractères de ponctuation 
a| * `*[:graph:]*` | -> | Caractère imprimable (incluant `*[:alnum:]*` et `*[:punct:]*`)
a| * `*[:print:]*` | -> | Caractère imprimable incluant l’espace 
a| * `*[:cntrl:]*` | -> | Caractère de contrôle 
|===
****

==== Caractères d'échappement

Les caractères d’échappement permettent de simplifier certains critères d’expressions. 

****
[grid=none,frame=none,cols="15,~,~"]
|===
a| * `*\n*` | -> | Nouvelle ligne
a| * `*\r*` | -> | Retour chariot
a| * `*\t*` | -> | Tabulation 
a| * `*\d*` | -> | `*\[[:digit:]]*` Des chiffres 
a| * `*\s*` | -> | `*\[[:blank:]]*` Des séparateurs 
a| * `*\w*` | -> | `*[[:alnum:]_]*` Tous les caractères alphanumériques et l’underscore
a| * `*\D*` | -> | `*[^[:digit:]]*` Tous sauf des chiffres 
a| * `*\S*` | -> | `*[^[:space:]]*` Tous sauf des séparateurs ( espace et tabulation ) 
a| * `*\W*` | -> | `*[^[:alnum:]_]*` Tous les caractères sauf les alphanumériques et l’underscore. 
a| * `*\u*` | -> | Le caractère suivant sera transformé en majuscule 
a| * `*\U*` | -> | Tous les caractères suivants seront transformés en majuscules jusqu’à `\E`
a| * `*\l*` | -> | Le caractère suivant sera transformé en minuscule 
a| * `*\L*` | -> | Tous les caractères suivants seront transformés en minuscules jusqu'à `\E` 
a| * `*\E*` | -> | Termine les `\L` et `\U` 
a| * `*\|*` | -> | "ou" en expression régulière.
1.2+a| * `*\*` 1.2+| -> | L’antislash est le banaliseur d’atome. 
| Exemple : `\*` correspond au caractère étoile et non au quantificateur étoile (répétition de 0 à n fois le caractère précédent) 
|===
****

==== Sous-expressions et références arrières

*Sous-expression* : partie d'une expression régulière encadrée par des parenthèses. Les parenthèses doivent être protégées par des antislashs. 

*Référence arrière* : pour réutiliser des sous-expressions, de 1 à 9. Elles doivent être protégées par des antislashs. Les sous-expressions sont numérotées de 1 à 9 par la parenthèse ouvrante.  

La référence arrière reprend exactement le résultat trouvé dans sa sous-expression de référence. 

****
`a\([bc]\)d\1` -> correspond à `abdb` ou `acdc`, mais pas `acdb` 
****

== Grep : Recherche d'expression dans les fichiers

