= Module 09 - Commandes de recherches
:navtitle: Commandes de recherches


* Module précédent -> xref:tssr2023/module-03/gestion-lien.adoc[Module 08 - Gestion des liens]
* Module suivant -> xref:tssr2023/module-03/editor-texte.adoc[Module 10 - Éditer du texte]

Notes -> xref:notes:eni-tssr:client-linux.adoc[Client Linux]

== Les Expressions régulières

=== Introduction aux expressions régulières

Une expression régulière est un modèle de chaînes de caractères auquel peut être associé un certain nombre de chaînes de caractères avec des caractéristiques communes : celles de l'expression régulière. 

Une expression régulière est construite à l'aide de différents caractères dont certains ont une signification particulière. Ce sont les caractères spéciaux (nommés aussi pass:[<u>atomes</u>]). 

Les expressions régulières sont utilisées par les outils d'édition et de recherche dans les fichiers tels que *vi*, *grep*, *sed*, *awk*, *ed*, *ex*, et autres. 

Il existe plusieurs versions d’expressions régulières. Nous verrons uniquement la version basique. 

Les atomes dans les expressions régulières sont des caractères générant une interprétation spécifique par l’application utilisant les expressions régulières. 

Les atomes d’expression régulière auront cette syntaxe : `*atome*`. 

Les caractères « normaux » celle-ci : `caractère`. 

==== Quantificateurs

Un atome quantificateur est un atome générant un comportement sur le caractère ou l’atome le précédant. 

.quantificateur
****
[grid=none,frame=none,cols="20,~,~"]
|===
//ligne 1
1.2+a| * `*` | -> |  Répétition du caractère qui précède de 0 à n fois
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `a*` ! Correspond à : `<rien>` ou `a` ou `aa` ou `aaa` …
!===
//ligne 2
1.2+a| * `\+` | -> |  Répétition du caractère qui le précède de 1 à n fois 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `a\+` ! Correspond à : `a` ou `aa` ou `aaa` …
!===
//ligne 3
1.2+a| * `\?` | -> |  Correspond à 0 ou 1 fois le caractère précédent 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `a\?` ! Correspond à : `<rien>` ou `a`.
!===
//ligne 4
1.2+a| * `car\{m,M\}` | -> |  Un caractère répété au minimum _m_ fois et au maximum _M_ fois 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `ab\{1,3\}c` ! Correspond à : `abc` ou `abbc` ou `abbbc` 
!===
//ligne 5
1.2+a| * `car\{n,\}` | -> |   Un caractère répété au minimum _m_ fois 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `es\{2,\}ai` ! Correspond à : essai, mais aussi à `esssai`, `essssai` … 
!===
//ligne 6
1.2+a| * `car\{n\}` | -> |  Un caractère répété _n_ fois exactement 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a!  `[A-Z]\{3\}` ! Correspond à une chaîne de caractères composée de 3 majuscules 
!===
|===
****

==== Atomes

****
[grid=none,frame=none,cols="25,~,~"]
|===
1.4+a| * `*.*` | -> | Un caractère quelconque
                       2.+|  Par exemple : 
                       2.+| `.` peut-être `a` `b` `c` `d` `ù` `3` etc.
                       2.+| `.*` correspond à une séquence de caractères quelconques : `<rien>` ou une suite d'un nombre quelconque de n'importe quel caractère 
1.2+a| * `*[liste, car]*` | -> | 1 seul caractère parmi ceux de la liste entre `[ ]`
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*[abc12]*` ! Correspond à : `a` ou `b` ou `c` ou `1` ou `2` 
!===
1.2+a| * `*[intervalle-caractères] [car. Début - car. Fin]*` | -> |  1 seul caractère dans l'intervalle 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*[A-Z]*` ! Correspond à une lettre majuscule 
a! `*[A-Za-z]*` ! Correspond à toutes les lettres minuscules et majuscules 
a! `*[a-h15]*` ! Correspond à un caractère `a` ou `b` ou `c` … ou `h` ou `1` ou `5` 
a! `*[h-m][08]*` ! Correspond à `h0` ou `h8` ou `i0` ou `i8` ... ou `m0` ou `m8` 
!===
1.2+a| * `*[^caractères]*` | -> | 1 seul caractère autre que ceux entre `*[]*` l’atome `*^*` dans les `*[]*` est la négation 
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*[^abc]*` ! Correspond à un caractère autre que `a` , `b` et `c` 
!===
1.2+a| * `*^chaîne*` | -> a| Chaîne de caractères placée en pass:[<u>début</u>] de ligne
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*^B*`  ! Une ligne qui commence par `B` 
a! `*^[aA\t]*`  ! Une ligne qui commence par `a` ou `A` ou par une `tabulation` 
a! `*^[ \t]**`  ! Une ligne qui commence par `*espace*` ou `*tabulation*` répétée de 0 à _n_ fois 
!===
1.2+a| * `*chaîne$*` | -> | Chaîne de caractères placée en pass:[<u>fin</u>] de ligne
2.+a|
[grid=none,frame=none,cols="20,~"]
!===
a! `*fin$*`  ! Une ligne qui se termine par `fin` 
a! `*[^xyz]$*`  ! Une ligne qui se termine par n'importe quel caractère autre que `x`, `y` ou `z`
a! `*^$*`  ! Une ligne vide 
a! `*^.*$*`  ! La totalité de la ligne quel que soit son contenu 
!===
|===
****

==== Classes de caractères

Les classes de caractères sont des regroupements thématiques de caractères. 

****
[grid=none,frame=none,cols="15,~,~"]
|===
a| * `*[:alpha:]*` | -> | Des lettres 
a| * `*[:upper:]*` | -> | Des majuscules 
a| * `*[:lower:]*` | -> | Des minuscules 
a| * `*[:digit:]*` | -> | Des chiffres décimaux 
a| * `*[:xdigit:]*` | -> | Des chiffres hexadécimaux 
a| * `*[:alnum:]*` | -> | Alphanumériques 
a| * `*[:blank:]*` | -> | Espaces ou tabulations
a| * `*[:space:]*` | -> | Espaces 
a| * `*[:punct:]*` | -> | Des caractères de ponctuation 
a| * `*[:graph:]*` | -> | Caractère imprimable (incluant `*[:alnum:]*` et `*[:punct:]*`)
a| * `*[:print:]*` | -> | Caractère imprimable incluant l’espace 
a| * `*[:cntrl:]*` | -> | Caractère de contrôle 
|===
****

==== Caractères d'échappement

Les caractères d’échappement permettent de simplifier certains critères d’expressions. 

****
[grid=none,frame=none,cols="15,~,~"]
|===
a| * `*\n*` | -> | Nouvelle ligne
a| * `*\r*` | -> | Retour chariot
a| * `*\t*` | -> | Tabulation 
a| * `*\d*` | -> | `*\[[:digit:]]*` Des chiffres 
a| * `*\s*` | -> | `*\[[:blank:]]*` Des séparateurs 
a| * `*\w*` | -> | `*[[:alnum:]_]*` Tous les caractères alphanumériques et l’underscore
a| * `*\D*` | -> | `*[^[:digit:]]*` Tous sauf des chiffres 
a| * `*\S*` | -> | `*[^[:space:]]*` Tous sauf des séparateurs ( espace et tabulation ) 
a| * `*\W*` | -> | `*[^[:alnum:]_]*` Tous les caractères sauf les alphanumériques et l’underscore. 
a| * `*\u*` | -> | Le caractère suivant sera transformé en majuscule 
a| * `*\U*` | -> | Tous les caractères suivants seront transformés en majuscules jusqu’à `\E`
a| * `*\l*` | -> | Le caractère suivant sera transformé en minuscule 
a| * `*\L*` | -> | Tous les caractères suivants seront transformés en minuscules jusqu'à `\E` 
a| * `*\E*` | -> | Termine les `\L` et `\U` 
a| * `*\|*` | -> | "ou" en expression régulière.
1.2+a| * `*\*` 1.2+| -> | L’antislash est le banaliseur d’atome. 
| Exemple : `\*` correspond au caractère étoile et non au quantificateur étoile (répétition de 0 à n fois le caractère précédent) 
|===
****

==== Sous-expressions et références arrières

*Sous-expression* : partie d'une expression régulière encadrée par des parenthèses. Les parenthèses doivent être protégées par des antislashs. 

*Référence arrière* : pour réutiliser des sous-expressions, de 1 à 9. Elles doivent être protégées par des antislashs. Les sous-expressions sont numérotées de 1 à 9 par la parenthèse ouvrante.  

La référence arrière reprend exactement le résultat trouvé dans sa sous-expression de référence. 

****
`a\([bc]\)d\1` -> correspond à `abdb` ou `acdc`, mais pas `acdb` 
****

== Grep : Recherche d'expression dans les fichiers

|===
^.^| Syntaxe : `*grep* [options] 'expression' <fichier>`
|===

.options
****
[grid=none,frame=none,cols="15,~,~"]
|===
a| *  `-c`            | -> | Nombre de lignes contenant l'expression 
a| *  `-h`            | -> | Suppression du nom de fichier lorsque la recherche est faite dans plusieurs fichiers
a| *  `-i`            | -> | Ignore la distinction minuscule et majuscule 
a| *  `-l`            | -> | Affiche uniquement le nom des fichiers contenant l'expression 
a| *  `-n`            | -> | Chaque ligne est précédée de son numéro dans le fichier 
a| *  `-v`            | -> | Affiche uniquement les lignes qui ne contiennent pas l'expression 
a| *  `-f <fichexpr>` | -> | Fichier dans lequel se trouve l'expression à rechercher 
a| *  `-e`            | -> | Option facultative qui précède l'expression à rechercher, il est possible d’indiquer plusieurs `-e` pour rechercher plusieurs expressions dans un fichier  
a| *  `'Expression'`  | -> | Expression régulière. Il est préférable de la protéger par des simples quotes 
a| *  `<fichier>`     | -> | Nom du fichier dans lequel la recherche doit être faite. Ce nom peut être générique. S'il n'est pas spécifié, la recherche est faite sur le canal d'entrée 
|===
****

Rechercher, sans tenir compte de la casse, les lignes qui commençant par `dupont` dans le fichier Edition : 

[source,bash]
----
$ grep -i '^dupont' Edition 
----

Vu que `grep` utilise les expressions régulières, il est fortement conseillé d'utiliser des simples quotes pour protéger l'expression de recherche. 

== Find : Recherche de fichiers selon des critères

|===
^.^| Syntaxe : `*find* <chemin> [critères] [action]`
|===

.options
****
[grid=none,frame=none,cols="15,~,~"]
|===
a| * `<chemin>` | -> | Nom du ou des répertoires à partir desquels la recherche va être faite. Si non spécifié, `find` commence sa recherche à partir de la position courante. 
1.2+a| * `[critères]` | -> | Critères de recherche qui permettent une sélection très précise des fichiers. Ces critères sont très nombreux, mais les suivants sont les plus courants : 
2.1+a|
[grid=none,frame=none,cols="30,~,~"]
!===
a! * `*-name "nomF"*` 2.+! Recherche en fonction du nom. Ce nom peut être générique et dans ce cas, il doit être protégé par des doubles quotes. 
a! * `*-user nom*` 2.+! Recherche des fichiers dont le user propriétaire est `nom`. 
a! * `*-group nom*` 2.+! Recherche des fichiers dont le groupe propriétaire est `nom`. 
1.6+a! * `*-type <t>*` 2.+! Recherche en fonction de la nature des fichiers. <t> peut prendre les valeurs suivantes : 
a! * `*f*` ! Fichier ordinaire
a! * `*d*` ! Répertoire 
a! * `*l*` ! Lien symbolique
a! * `*b*` ! Fichier spécial en mode bloc
a! * `*c*` ! Fichier spécial en mode caractère
3.+a! * `*-perm [-] <perms>*` 
! 2.+! Recherche en fonction des droits. `perms` peut être exprimé en notation octale ou symbolique. Si la valeur de `perms` est négative, seuls les fichiers dont les droits sont au moins perms seront retenus. Dans le cas d'une valeur positive, les fichiers retenus seront ceux pour lesquels les droits sont strictement égaux à `perms` 
a! * `*-size nb [c]*` 2.+! Recherche en fonction de la taille des fichiers exprimée en blocs (de 512 octets) ou en octets si nb est suivi du caractère c.  Pour une comparaison en blocs, la taille des fichiers est arrondie au bloc supérieur. Une comparaison octets impose que le ou les fichiers recherchés aient exactement le même nombre d'octets que celui spécifié par l'option `-size`. 
a! * `*-newer <nom>*` 2.+! Recherche les fichiers dont la date de modification est plus récente que la date de modification du fichier nom. 
a! * `*-atime <nb>*` 2.+! Recherche des fichiers sur la date de dernier accès, nb correspond au nombre de jours (1 pour la veille, 2 pour 2 jours avant, 3 pour 3 jours avant…) 
a! * `*-ctime <nb>*` 2.+! Recherche des fichiers sur la date de création ou de dernière modification 
a! * `*-mtime <nb>*` 2.+! Recherche des fichiers sur la date de dernière modification 
a! * `*-inum <num>*` 2.+! Recherche des fichiers sur le numéro d'inode 
!===
1.2+a| * `[actions]` | -> | Les actions sont exécutées pour chaque occurrence trouvée par find. 
2.1+a|
[grid=none,frame=none,cols="30,~"]
!===
a! * `*-printf*` a! Permet de n’afficher que les informations souhaitées pour chaque résultat trouvé 

Exemple : 

[source,bash]
----
$ find /boot –name "*.cfg" –printf “%f” 
----
Recherche à partir de /boot tous les fichiers finissant par “.cfg” et n’affiche que le nom de chaque fichier trouvé 

a! * `*-print*` ! Affichage des noms de fichiers trouvés au fur et à mesure 
2.+a! * `*-exec cmd [options] {} \;*` 
! a! 
Pour chaque fichier trouvé, exécution de la commande cmd. Le nom de chaque fichier est symbolisé par `{}` . La commande se  termine obligatoirement par un espace suivi des caractères  `\;` 

Exemple :

[source,bash]
----
$ find /home –type f –name "*.txt" –exec ls –l {} \; 
----

Recherche à partir de /home tous les fichiers de type standard finissant par “.txt” et exécute un `ls –l` à chaque fichier trouvé 

2.+a! * `*-ok cmd [options] {} \;*` 
! ! Identique à `-exec` avec demande de confirmation pour chaque exécution de cmd 
!===
|===
****

=== Regroupement et opérateurs dé sélections

Il est possible avec `find` de regrouper des critères de recherche et d’ajouter des opérateurs de sélection. 

Les regroupements seront à encadrer par des parenthèses précédées d’un antislash. 

Les différents opérateurs sont :  

* `*!*`  : Opérateur de négation
* `*-o*` : Opérateur OU (Or)
* `*-a*` : Opérateur ET (And)

Exemple : 

Rechercher des fichiers standards se terminant par `.txt` et des répertoires se terminant par `perso` dans les répertoires d’accueil des utilisateurs : 

[source,bash]
----
$ find /home \( -type f -name "*.txt" \) -o \( -type d –name "*perso" \) 
----

=== Exemples

Rechercher dans le répertoire /etc les fichiers réguliers ayant l'inode 24621 : 

[source,bash]
----
$ find /etc -type f -inum 24621 
----

Rechercher dans son répertoire d'accueil les fichiers suffixés en .tmp et les supprimer : 

[source,bash]
----
$ find $HOME -type f -name "*.tmp" -exec rm {} \; 
----

== TP

Réalisation du TP N° 5 : xref:procedures:tp-eni:tssr2023/client-linux/TP05.adoc[Recherche de contenu et de fichiers]