= Module 09 - Commandes de recherches
:navtitle: Commandes de recherches


* Module précédent -> xref:tssr2023/module-03/gestion-lien.adoc[Module 08 - Gestion des liens]
* Module suivant -> xref:tssr2023/module-03/cmd-recherches.adoc[Module 07 - Afficher du texte]

Notes -> xref:notes:eni-tssr:client-linux.adoc[Client Linux]

== Les Expressions régulières

=== Introduction aux expressions régulières

Une expression régulière est un modèle de chaînes de caractères auquel peut être associé un certain nombre de chaînes de caractères avec des caractéristiques communes : celles de l'expression régulière. 

Une expression régulière est construite à l'aide de différents caractères dont certains ont une signification particulière. Ce sont les caractères spéciaux (nommés aussi pass:[<u>atomes</u>]). 

Les expressions régulières sont utilisées par les outils d'édition et de recherche dans les fichiers tels que *vi*, *grep*, *sed*, *awk*, *ed*, *ex*, et autres. 

Il existe plusieurs versions d’expressions régulières. Nous verrons uniquement la version basique. 

Les atomes dans les expressions régulières sont des caractères générant une interprétation spécifique par l’application utilisant les expressions régulières. 

Les atomes d’expression régulière auront cette syntaxe : `*atome*`. 

Les caractères « normaux » celle-ci : `caractère`. 

==== Quantificateurs

Un atome quantificateur est un atome générant un comportement sur le caractère ou l’atome le précédant. 

.quantificateur
****
[grid=none,frame=none,cols="~,~,~"]
|===
//ligne 1
a| * `*` | -> |  Répétition du caractère qui précède de 0 à n fois
|        |    a|
[grid=none,frame=none,cols="~,~"]
!===
a!  `a*` ! Correspond à : `<rien>` ou `a` ou `aa` ou `aaa` …
!===
//ligne 2
a| * `\+` | -> |  Répétition du caractère qui le précède de 1 à n fois 
|        |    a|
[grid=none,frame=none,cols="~,~"]
!===
a!  `a\+` ! Correspond à : `a` ou `aa` ou `aaa` …
!===
//ligne 3
a| * `\?` | -> |  Correspond à 0 ou 1 fois le caractère précédent 
|        |    a|
[grid=none,frame=none,cols="~,~"]
!===
a!  `a\?` ! Correspond à : `<rien>` ou `a`.
!===
//ligne 4
a| * `car\{m,M\}` | -> |  Un caractère répété au minimum _m_ fois et au maximum _M_ fois 
|        |    a|
[grid=none,frame=none,cols="~,~"]
!===
a!  `ab\{1,3\}c` ! Correspond à : `abc` ou `abbc` ou `abbbc` 
!===
//ligne 5
a| * `car\{n,\}` | -> |   Un caractère répété au minimum _m_ fois 
|        |    a|
[grid=none,frame=none,cols="~,~"]
!===
a!  `es\{2,\}ai` ! Correspond à : essai, mais aussi à `esssai`, `essssai` … 
!===
//ligne 6
a| * `car\{n\}` | -> |  Un caractère répété _n_ fois exactement 
|        |    a|
[grid=none,frame=none,cols="~,~"]
!===
a!  `[A-Z]\{3\}` ! Correspond à une chaîne de caractères composée de 3 majuscules 
!===
|===
****