= Module 06 - Les caractères spéciaux
:navtitle: Caractères Spéciaux


* Module précédent -> xref:tssr2023/module-03/arborescence.adoc[Module 05 - Arborescence Unix / Linux]
* Module suivant -> xref:tssr2023/module-03/show-texte.adoc[Module 07 - Afficher du texte]

Notes -> xref:notes:eni-tssr:client-linux.adoc[Client Linux]

Les commandes de gestion de fichiers autorisent l'utilisation de métacaractères qui peuvent être combinés avec des caractères dits spéciaux

== Métacaractères

Les métacaractères sont des caractères de substitution utilisés pour définir des noms génériques. 

Ces caractères sont les suivants : 

****
[frame=none,grid=none,cols="18,~,~"]
|===
a|* `*`           | -> | 0 à n caractères
a|* `?`           | -> | 1 caractère quelconque et un seul
a|* `[...]`       | -> | 1 seul caractère parmi ceux de la liste entre `[ ]` (crochets)
a|* `[...-...]`   | -> | 1 seul caractère compris dans l'intervalle de caractères, bornes incluses
a|* `^[...]`      | -> | Négation, 1 seul caractère autre que ceux spécifiés entre `[ ]` ( `!` est aussi valable `[!...]`) 
|===
****

Pour spécifier un crochet, il faut le placer immédiatement après le crochet ouvrant. 

=== Exemples

****
[frame=none,grid=none,cols="25,~,~"]
|===
a|* `*.c`         | -> | Tous les noms qui se terminent par " .c " 
a|* `ab?h`        | -> | Tous les noms de quatre caractères qui commencent par "ab" et se terminent par "h", la valeur du troisième caractère est quelconque 
a|* `ab[bhmp]15`  | -> | Tous les noms de cinq caractères qui commencent par "ab" et se terminent par "15", la valeur du troisième caractère est "b" ou "h" ou "m" ou "p" 
a|* `ab[a-h1-5]2` | -> | Tous les noms de quatre caractères qui commencent par "ab" et se terminent par "2", la valeur du troisième caractère doit être comprise entre "a" et "h" ou entre "1" et "5" 
a|* `ab[!aei]h`   | -> | Tous les noms de quatre caractères qui commencent par "ab" et se terminent par "h" dont le troisième caractère n'est pas "a" ou "e" ou "i" 
a|* `[A-Z]`       | -> | 1 caractère parmi les lettres majuscules 
a|* `[A-Za-z]`    | -> | 1 caractère parmi toutes les lettres minuscules et majuscules 
|===
****

[IMPORTANT]
====
ATTENTION à l'ordre des caractères des séquences. 

En Bourne Shell, les caractères sont séquencés comme ceci : 

[source,shell]
----
abcd....xyzABC....XYZ 
----

Alors que le Bash les aligne de cette façon : 
[source,shell]
----
aAbBcC...xXyYzZ   et en incluant les caractères accentués (éêè...) 
----

====

=== Classes de caractères

Il est possible d'utiliser une des classes de caractères suivantes : 
****
[frame=none,grid=none,cols="12,~,~"]
|===
a|* `[:cntrl:]`   | -> | Caractère de contrôle 
a|* `[:space:]`   | -> | Espace blanc ou séparateur de ligne ou de paragraphe 
a|* `[:blank:]`   | -> | Espace blanc ou tabulation non séparateur de ligne ou de paragraphe 
a|* `[:print:]`   | -> | Espace simple ou caractère graphique visible 
a|* `[:graph:]`   | -> | Caractère graphique visible 
a|* `[:punct:]`   | -> | Caractère de ponctuation 
a|* `[:alnum:]`   | -> | Caractère alphanumérique 
a|* `[:digit:]`   | -> | Chiffre décimal 
a|* `[:xdigit:]`  | -> | Chiffre hexadécimal 
a|* `[:alpha:]`   | -> | Caractère alphabétique 
a|* `[:lower:]`   | -> | Lettre minuscule 
a|* `[:upper:]`   | -> | Lettre capitale 
|===
****

.En utilisant la syntaxe : 
[source,regex]
----
[[:classe:]] 
----

=== Les expressions complexes

En plus des métacaractères, les environnements `ksh` et `bash` disposent d'expressions complexes permettant d'étendre les possibilités de remplacement de caractères. Ces options permettent notamment la prise en charge de facteurs d’occurrences. 

==== Facteurs d'occurrences

****
[frame=none,grid=none,cols="20,~,~"]
|===
a|* `?( … )` | -> |  0 à 1 fois l'expression entre parenthèses 
a|* `*( … )` | -> |  0 à n fois l'expression entre parenthèses 
a|* `+( … )` | -> |  1 à n fois l'expression entre parenthèses 
a|* `@( … )` | -> |  1 fois l'expression entre parenthèses 
a|* `!( … )` | -> |  L'expression entre parenthèses ne sera pas présente 
|===
****

[NOTE]
====

il faudra s'assurer que l'utilisation des expressions complexes est activée grâce à l'option *extglob* : 

[source,shell]
----
$ shopt 
$ shopt -s extglob 
----
====

=== Énumération d'une expression

Comme pour les caractères, il est possible d'offrir un choix d'expressions, en utilisant les caractères `{}` (accolades) : 

* `{chaîne1,chaîne2,chaîne3} ` ->  chaîne1 ou chaîne2 ou chaîne3 

Afficher les fichiers ayant l'extension txt, odt ou doc : 

[source,shell]
----
$ ls fichier.{txt,odt,doc} 
----

== Caractères spéciaux

En plus des métacaractères, le Shell interprète de façon particulière certains caractères appelés caractères spéciaux. 

Ces caractères sont les suivants : 

[frame=none,grid=none,cols="15,~,~,~"]
|===
a|* `'    ' `  | -> |  Simple quote | Banalise tous les caractères situés entre les simples quotes
 |              |    |              a| 
[source,shell]
----
$ echo 'prix : 15$50' 
$ prix : 15$50 
----

a|* `""    "" `|   -> |  Double quote | Banalise tous les caractères situés entre les doubles quotes sauf :  `$`    ```    `\`  (dollar, backquote et antislash) 
||| a| 
[source,shell]
----
$ echo "aujourd'hui, vous êtes connecté sur $HOSTNAME" 
$ aujourd’hui, vous êtes connecté sur SRVFIC-01 
----

a|* ` \ ` |  -> |  Antislash | Banalise le caractère suivant lorsque celui-ci est évalué comme un caractère spécial ou un délimiteur. 
A contrario, peut donner une signification particulière à un caractère situé après. 
||| a| 
[source,shell]
----
$ echo "prix : 15\$50" 
$ prix : 15$50 
----

a|* ` $ ` |  -> |  Dollar | Permet d'afficher le contenu d'une variable
a|* ` $(...) ` |  -> |  Dollar parenthèse | Permet l'utilisation du résultat d'une commande 
|              |     |                    a| *Il est préférable d’utiliser `pass:[`…`]` sur les distributions anciennes.*
|===



== TP

Réalisation du TP N° 2 : xref:procedures:tp-eni:tssr2023/client-linux/TP02.adoc[Manipuler des fichiers]