= Module 03 - Le Shell
:navtitle: Shell


* Module précédent -> xref:tssr2023/module-03/premier-pas.adoc[Module 02 - Les premier pas et les premières commandes]
* Module suivant -> xref:tssr2023/module-03/shell.adoc[Module 04 - Le Shell]

Notes -> xref:notes:eni-tssr:client-linux.adoc[Client Linux]

== Le shell : Interpréteur de commande

Le Shell est un programme permettant les échanges entre le système Linux et l'utilisateur : c'est un interpréteur de commandes. 

Son utilisation s'étend à la programmation, grâce à la gestion des variables, des boucles, et des flux Entrée / Sortie. 

Plusieurs Shell sont disponibles sur les systèmes GNU/Linux. 

=== Les principaux interpréteurs de commandes

Le Shell considéré le plus ancien est le Bourne Shell (sh), du nom de son créateur Steve Bourne. 

Bill Joy créa quant à lui le C-Shell (csh), incompatible avec le Bourne shell mais permettant le rappel de commandes, le contrôle des tâches et l'utilisation des alias de commandes. 

Plus tard, David Korn repris le Bourne Shell en y incluant les fonctionnalités du C-shell. Ce nouvel interpréteur prendra lui aussi le nom de son créateur en s'appelant le Korn Shell (ksh). C'est le Shell le plus utilisé des systèmes UNIX commerciaux. 

Le projet GNU développera aussi son alternative aux Shell existants avec le Bourne Again Shell (bash), conforme comme le ksh à la norme POSIX en y ajoutant quelques extensions. C'est l'interpréteur de commande fourni en standard sur les distributions Linux. 

Les principales différences : 

* Historique dans csh et ksh 
* Éditeur de lignes dans ksh 
* Les syntaxes des boucles diffèrent entre csh, ksh et sh : 
* csh : while … end 
* ksh et sh : while … do … done 
* Goto n'existe qu'en csh 
* Le mécanisme de substitution des variables ksh est plus élaboré L'arithmétique entière n'existe qu'en csh et ksh 
* Le mécanisme d'alias (abréviation de commande) n'existe qu'en csh et ksh 

Particularité sur les systèmes d'exploitation AIX, le Bourne Shell s'appelle bsh. 

=== Quel Shell utiliser dans un programme ?

Le Korn Shell et le Bash ont une compatibilité descendante avec le Bourne Shell, aussi, l'écriture d'un script en Bourne Shell assure la meilleure portabilité possible. Il comporte cependant quelques lacunes et certaines fonctionnalités font défaut, c'est pourquoi il est possible de lui préférer le Korn Shell ou le Bash. 

Nous abordons dans ce cours le sh et le bash. Ne serons pas vus le csh, le tcsh, le ash, le dash, ni même le zsh. 

=== Les variables

Les données d’un système peuvent être stockées sur un disque dur ou en mémoire vive. Un disque dur permet de stocker des données sous forme de fichiers. Le Shell permet l’enregistrement de données en mémoire vive sous forme de variables. 

==== Liste les variables déclarées

Pour afficher la liste des variables et leur contenu, on utilise les commandes suivantes : 

[source,bash]
----
$ set
----

Affiche toutes les variables 

[source,bash]
----
$ env
----

Affiche uniquement la liste des variables d’environnement* 

|===
^.^| * | Les variables et leur gestion sont abordées de manière détaillée en Scripting Shell. 
|===

==== Quelques variables d'environnement

Il existe beaucoup de variables d'environnement, certaines sont importantes : 

****
* `HOME`     ->  Répertoire de connexion 
* `~`        ->  Répertoire de connexion
* `PATH`     ->  Chemin de recherche des exécutables (séparés par des "`:`")
* `LOGNAME`  ->  Nom du user de connexion 
* `MAIL`     ->  Chemin d'accès au fichier boîte aux lettres 
* `PS1`      ->  Prompt du Shell 
* `PS2`      ->  Prompt de continuation 
* `SHELL`    ->  Shell de connexion 
****

== Le rappel de commandes, historique, autocompletion

Les facilités offertes par le rappel des commandes et l'autocomplétion dans un Shell telles que le Bash lui procurent un rendement très intéressant, à tel point qu'il est bien souvent plus efficace de se déplacer et d'exécuter des commandes dans un terminal plutôt que par le biais d'une interface graphique. 

=== Historique et rappel de commandes

****
* `↑`       -> Rappeler les commandes précédentes, on peut remonter dans tout l'historique des commandes 
* `↓`       -> Rechercher dans l'ordre inverse 
* `!!`      -> Rappeler la dernière commande exécutée 
* `!com`    -> Rappeler la dernière commande exécutée commençant par la chaîne "com"
* `!?fich`  -> Rappeler la dernière commande exécutée contenant la chaîne "fich" 
* `history` -> Afficher les commandes mémorisées 
* `!287`    -> Rappelle la commande numérotée 287 
****

Avec l’expérience et l’usage répété de la ligne de commandes, on constatera que le rappel de commandes reste disponible pour les utilisateurs et ce même après avoir fermé sa session ou redémarré l'ordinateur. Cela signifie donc que les commandes déjà saisies sont conservées dans un fichier. Quel est-il ? Combien de commandes sont mémorisées ? Quels sont les paramètres passés au rappel de commande ? 

Les réponses se trouvent dans des variables : 
****
* `HISTCMD`           -> Contient le dernier numéro de commande utilisée 
* `HISTFILE`          -> Chemin et nom du fichier de rappel 
* `HISTFILESIZE`      -> Taille du nombre de rappels possibles 
* `HISTSIZE`          -> Taille du nombre de commandes en mémoire 
* `HISTCONTROL`       -> Liste des options au rappel de commandes 
* `HISTTIMEFORMAT`    -> N'est généralement pas présente par défaut, il permet d'horodater les commandes saisies. 
****

On pourra par exemple pour le compte root, par mesure de sécurité, ajouter dans le fichier `.bashrc` la déclaration de la variable comme ceci : 

`export HISTTIMEFORMAT="%Y/%m/%d @ %T"`

=== Autocomplétion

Le Bash permet la complétion automatique, c'est-à-dire l'incrémentation automatique des noms lors de la frappe. L'autocomplétion est activée en pressant une ou deux fois la touche `[Tabulation]`. 

L'autocomplétion agit sur plusieurs niveaux : 

==== Les chemins d'accès

L'autocomplétion est très utilisée pour les chemins d'accès. 

.Exemple : 
[source,shell]
----
$ ls /e 
----

Suivi de la touche `[Tabulation]`, le chemin /etc se verra automatiquement complété : 

[source,shell]
----
$ ls /etc
----

Si l'autocomplétion n'agit pas, c'est que les premiers caractères saisis offrent plusieurs possibilités. En appuyant sur la touche `[Tabulation]` deux fois de suite, cela affichera les différentes options possibles. 

Ainsi, la commande suivante 

[source,shell]
----
$ ls /etc/h 
----

Suivie d'une double frappe sur la touche `[Tabulation]` pourra donner ceci : 

[source,shell]
----
hdparm.conf host.conf hostname hosts hosts.allow hosts.deny   
----

==== Les commandes

Les commandes bénéficient également de l'autocomplétion : 

[source,shell]
----
fir 
----

Suivi de la touche `[Tabulation]` donnera : 


[source,shell]
----
firefox 
----

==== Les variables

Même chose pour les variables : 

[source,shell]
----
echo $LO 
----

Ce qui donnera : 

[source,shell]
----
echo $LOGNAME 
----

NOTE: Certains environnements étendent l'autocomplétion encore plus loin, par exemple aux pages de man ou aux options sur certaines commandes. 