= Module 07 - Afficher du texte
:navtitle: Afficher du texte


* Module précédent -> xref:tssr2023/module-03/metacaractere.adoc[Module 06 - Les caractères spéciaux]
* Module suivant -> xref:tssr2023/module-03/show-texte.adoc[Module 07 - Afficher du texte]

Notes -> xref:notes:eni-tssr:client-linux.adoc[Client Linux]

== Cat : Affichage et concaténation de fichiers


|===
^.^| Syntaxe : `*cat* [options] <fichier> <fichier>`
|===


.options
****
[grid=none,frame=none,cols="~,~,~"]
|===
a| * `-n` | -> |  Affiche les numéros de lignes (identique à la commande `nl`)
a| * `-b` | -> | Affiche les numéros de lignes non vides 
a| * `-s` | -> | N'affiche pas les lignes vides consécutives 
a| * `fichier` | -> | Nom (éventuellement générique) du ou des fichiers 
|===
****

Si plusieurs fichiers sont concernés par la commande `cat`, le contenu de chacun d'eux sera concaténé. 

Si aucun fichier n'est spécifié, la commande `cat` attend son flux d'entrée via le clavier et ne s'exécutera qu'à la réception de fin de flux d'entrée par les touches `[Ctrl] + [d]` sur une ligne vide. 

[source, shell]
----
$ cat /etc/passwd 
stag01:x:1033:1034::/home2/stag01:/bin/sh 
stag02:x:1034:1035::/home2/stag02:/bin/sh 
stag03:x:1035:1036::/home2/stag03:/bin/sh 
[...] 
stag30:x:1062:1063::/home2/stag30:/bin/sh 

$ cat > listing_nouveaux_utilisateurs 

>Eric   Legrand 
>Benoit   Empawindoz 
[ctrl] + [d] 
$
$ cat legende_users 
PRENOM    NOM
-----------------------------

$ cat legende_users listing_nouveaux_utilisateurs 
PRENOM    NOM
-----------------------------
Eric   Legrand 
Benoit   Empawindoz 
----

== More : Visualisation avec pause à chaque page-écran


|===
^.^| Syntaxe : `*more* [options] [-nblig ] <nomFichier>`
|===


.options
****
[grid=none,frame=none,cols="~,~,~"]
|===
a| *  `-d`  | ->  |  Affiche un message d’aide en bas de page 
| |   |  [Hit space to continue, Del to abort] 
a| *  `-s`  | ->  | Ne conserve qu’une ligne blanche si plusieurs lignes blanches consécutives 
a| *  `-nblig`  | ->  | Définit le nombre de lignes de la page de visualisation, exemple : `-15` 
a| *  `nomFichier`  | ->  | Nom du fichier à traiter. Ce nom peut être générique. À défaut de nom, la commande travaille sur le flux d’entrée. 
|===
****

[source,shell]
----
$ more /etc/passwd 
stag01:x:1033:1034::/home2/stag01:/bin/sh 
stag02:x:1034:1035::/home2/stag02:/bin/sh 
stag03:x:1035:1036::/home2/stag03:/bin/sh 
stag04:x:1036:1037::/home2/stag04:/bin/sh 
stag05:x:1037:1038::/home2/stag05:/bin/sh 
stag06:x:1038:1039::/home2/stag06:/bin/sh 
stag07:x:1039:1040::/home2/stag07:/bin/sh 
stag08:x:1040:1041::/home2/stag08:/bin/sh 
stag09:x:1041:1042::/home2/stag09:/bin/sh 
stag10:x:1042:1043::/home2/stag10:/bin/sh 
stag11:x:1043:1044::/home2/stag11:/bin/sh 
stag12:x:1044:1045::/home2/stag12:/bin/sh 
--More--(56%) 
----

À ce stade de l’affichage, il est possible d’exécuter un certain nombre de commandes. 

Les commandes `h` et `?` permettent d’obtenir l’aide en ligne des sous-commandes de `more`. 

La touche `v` permet quant à elle de faire appel à l’éditeur `vi`. 

== Less :  Visualisation avec pause à chaque page-écran

Similaire dans son principe à la commande `more`, `less`, commande très utilisée sur les environnements Linux, en améliore le fonctionnement. Cette commande est cependant moins répandue sur d'anciens systèmes UNIX. 


|===
^.^| Syntaxe : `*less* [options]  <fichier1> <fichier2>`
|===

La commande `less` offre l'avantage de ne pas quitter la lecture du fichier lorsque le curseur arrive à la fin du fichier. D'autre part, la recherche de chaînes de caractères est plus lisible. 

Un très grand nombre d'options est disponible pour cette commande, en voici quelques-unes : 

.options
****
[grid=none,frame=none,cols="~,~,~"]
|===
a| *  `i` ou `I`  | ->  | Permet d'ignorer la casse dans la recherche d'occurrences
a| *  `S`         | ->  | Supprime les doublons de lignes vides 
|===
****

Quelques commandes à effectuer lors de la lecture : 

.commande
****
[grid=none,frame=none,cols="~,~,~"]
|===
a| *  `h`         | ->  | Accéder à l'aide 
a| *  `q`         | ->  | Quitter le fichier ou l'aide 
a| *  `/Rigel`    | ->  | Rechercher la chaîne _Rigel_ 
 |                | ->  |  `n`  Pour continuer la recherche vers le bas
 |                | ->  |  `N`  Pour continuer la recherche vers le haut
a| *  `G`         | ->  | Positionne en fin de fichier 
a| *  `gg`        | ->  | Positionne en début de fichier
|===
****

== Head : Affichage des première lignes d'un  fichier

|===
^.^| Syntaxe : `*head* [options]  <nomFichier(s)>`
|===


.options
****
[grid=none,frame=none,cols="~,~,~"]
|===
a| *  `-n nbl`         | -> |
a| *  `-c nb`         | -> |
a| *  `-v`         | -> |
a| *  ``         | -> |
a| *  ``         | -> |
a| *  ``         | -> |
a| *  ``         | -> |
a| *  ``         | -> |
a| *  ``         | -> |
a| *  ``         | -> |
|===
****