= Administration Systèmes Linux


== Rappel

* *BIOS* =  **B**asic **I**nput **O**utput **S**ystem
* *MBR* = Norme crée en 1983

Le *bios* lance une séquence de démarrage à la recherche du secteur de boot sur un disque  MBR/GPT (GRUB1)

Grub1 part à la recherche de la partition d'amorçage identifié par un flag de boot (GRUB2)

Grub2 va charger `Linux Kernel` (Vmlinuz, initrd) va lancer Init=/sbin/init qui est un lien symbolique vers Systemd Root=Périphérique contenante la racine

Systemd lance la cible par défaut (multi-user.target ou graphical.target)

== LVM

Les système de fichier unix sont segmenté en *blocs de donnée*, chaque bloc vaut *4ko*

Chaque bloc puet avoir différent structure

* *tune2fs* : permet de modifier des options d’un système de fichier type ext. Il permet aussi de
récupérer les informations du superblock.

echo "- - -" > /sys/class

.commandeSpecial
[source, shell]
----
echo "- - -" > /sys/class/scsi_host/host2/scan
udevadm info --query=path --name=sda
 xxd
----

== TP

* xref:tssr2023/module-04/tp/tp7.adoc[TP7 - Gestion des espaces disque]
* xref:tssr2023/module-04/tp/tp8.adoc[TP8 - Gestion des systèmes de fichiers et montage]
* xref:tssr2023/module-04/tp/tp11.adoc[TP11 - Gestion de la journalisation]
* xref:tssr2023/module-04/tp/tp12.adoc[TP12 - Utilisation crontab]

== Montage

* *mount*

* *pcd-dss* : https://www.google.com/search?q=pci-dss&rlz=1C1GCEJ_enFR1052FR1052&oq=pci-dss&aqs=chrome..69i57j0i512l7j0i30l2.2887j0j4&sourceid=chrome&ie=UTF-8

== log

emerg, alert, crit, err, warning, notice, info, debug.


Commande pratique : watch, toutes 2 secondes, éxécute une commande.